import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        beige: 'var(--beige)',
        'bong-orange': 'var(--bong-orange)',
        'bong-orange-bg': 'var(--bong-orange-bg)',
        'envelope-bg': '#F6EEDA',
        'loading-gray': '#4A4A4A',
        primary: 'var(--bt-text-title)',
        accent: 'var(--bt-accent)',
        base: 'var(--bt-surface)',
        'base-muted': 'var(--bt-page-bg)',
        bt: {
          page: 'var(--bt-page-bg)',
          surface: 'var(--bt-surface)',
          card: 'var(--bt-card)',
          ink: 'var(--bt-text)',
          strong: 'var(--bt-text-strong)',
          title: 'var(--bt-text-title)',
          body: 'var(--bt-text-body)',
          muted: 'var(--bt-text-muted)',
          subtle: 'var(--bt-text-subtle)',
          meta: 'var(--bt-text-meta)',
          emphasis: 'var(--bt-text-emphasis)',
          'emphasis-strong': 'var(--bt-text-emphasis-strong)',
          /** Canonical text scale */
          'text-primary': 'var(--bt-text-primary)',
          'text-secondary': 'var(--bt-text-secondary)',
          /** ěš´ë?? ??ëŞŠÂˇę°?ěĄ° (??ëŞŠ=?¤ě´ëš? ëś???ëł¸ëŹ¸ ?? */
          'card-title': 'var(--bt-card-title)',
          'card-subtitle': 'var(--bt-card-subtitle)',
          'icon-accent': 'var(--bt-icon-accent)',
          /** ?źÂˇí?­ ???¸í?°??ě?? ??ë?ëŚ?(ë¸?ëŁ¨) */
          'ui-accent': 'var(--bt-ui-accent)',
          'ui-accent-soft': 'var(--bt-ui-accent-soft)',
          inverse: 'var(--bt-text-inverse)',
          disabled: 'var(--bt-disabled)',
          price: 'var(--bt-price)',
          border: 'var(--bt-border)',
          'border-soft': 'var(--bt-border-soft)',
          'border-strong': 'var(--bt-border-strong)',
          'surface-soft': 'var(--bt-surface-soft)',
          'surface-alt': 'var(--bt-surface-alt)',
          link: 'var(--bt-link)',
          'link-hover': 'var(--bt-link-hover)',
          success: 'var(--bt-success)',
          warning: 'var(--bt-warning)',
          danger: 'var(--bt-danger)',
          brand: {
            gold: 'var(--bt-brand-gold)',
            'gold-strong': 'var(--bt-brand-gold-strong)',
            blue: 'var(--bt-brand-blue)',
            'blue-strong': 'var(--bt-brand-blue-strong)',
            'blue-soft': 'var(--bt-brand-blue-soft)',
          },
          accent: 'var(--bt-accent)',
          'accent-hover': 'var(--bt-accent-hover)',
          'accent-subtle': 'var(--bt-accent-subtle)',
          'accent-fg': 'var(--bt-accent-fg)',
          'cta-primary': 'var(--bt-cta-primary-bg)',
          'cta-primary-hover': 'var(--bt-cta-primary-hover)',
          'cta-primary-fg': 'var(--bt-cta-primary-text)',
          'cta-secondary': 'var(--bt-cta-secondary-bg)',
          'cta-secondary-text': 'var(--bt-cta-secondary-text)',
          'cta-secondary-border': 'var(--bt-cta-secondary-border)',
          'cta-accent': 'var(--bt-cta-accent-bg)',
          'cta-accent-text': 'var(--bt-cta-accent-text)',
          badge: 'var(--bt-badge-bg)',
          'badge-ink': 'var(--bt-badge-text)',
          'badge-package': 'var(--bt-badge-package)',
          'badge-package-text': 'var(--bt-badge-package-text)',
          'badge-freeform': 'var(--bt-badge-freeform)',
          'badge-freeform-text': 'var(--bt-badge-freeform-text)',
          'badge-domestic': 'var(--bt-badge-domestic)',
          'badge-domestic-text': 'var(--bt-badge-domestic-text)',
          supplier: 'var(--bt-supplier-label)',
          'cal-available': 'var(--bt-calendar-available)',
          'cal-unavailable': 'var(--bt-calendar-unavailable)',
          'cal-selected': 'var(--bt-calendar-selected)',
          'cal-lowest': 'var(--bt-calendar-lowest)',
          domestic: 'var(--bt-domestic)',
          overseas: 'var(--bt-overseas)',
          disclosure: 'var(--bt-disclosure-bg)',
          /** ëł¸ëŹ¸ ěš´ë?? ę°?ěĄ°(?? ??CTA/??ë¸?ëŁ¨?? ëł?ë? */
          'card-accent': 'var(--bt-card-body-accent)',
          'card-accent-strong': 'var(--bt-card-body-accent-strong)',
          'card-accent-soft': 'var(--bt-card-body-accent-soft)',
          'card-accent-border': 'var(--bt-card-body-accent-border)',
        },
      },
      fontFamily: {
        sans: [
          'Pretendard',
          'var(--font-noto-sans-kr)',
          'Apple SD Gothic Neo',
          'Malgun Gothic',
          'system-ui',
          'sans-serif',
        ],
      },
      keyframes: {
        'partner-org-marquee': {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        'group-meeting-reviews-marquee': {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
      animation: {
        /** ëĄ?ęł  ??ěź ??ë°?í??ëłľě ? ??ěź 2ě¤?ę¸°ě? translateX -50%) */
        'partner-org-marquee': 'partner-org-marquee 52s linear infinite',
        'group-meeting-reviews-marquee': 'group-meeting-reviews-marquee 92s linear infinite',
      },
    },
  },
  plugins: [],
}
export default config
