/**
 * Canonical column keys for 봉심 Excel ingest (Korean row-2 headers ↔ English mirror).
 * Values are stable DB field fragments; normalization fills `BongsimProductOptionV1`.
 */
export const BONGSIM_EXCEL_COLUMN_MAP = {
  ko: {
    sim_type: "심타입",
    update_type: "변경구분",
    vendor_code: "공급사코드",
    plan_name: "플랜명",
    days: "일수",
    allowance: "용량",
    option_name: "옵션명",
    option_api_id: "옵션ID(API)",
    carrier: "통신사",
    data_class: "데이터 구분",
    network: "네트워크",
    internet: "망",
    qos: "QOS",
    validity: "유효기간",
    apn: "APN",
    install_benchmark: "설치 기준",
    kyc: "신원인증",
    hotspot: "핫스팟",
    activation_policy: "활성화 정책",
    mcc: "MCC",
    mnc: "MNC",
    esim: "eSIM",
    usim: "USIM",
    request_shipment: "요청(발송)",
    status_check: "상태\n(설치,사용량 등)",
    extension: "연장\n(동일한 ICCID \n추가 탑업)",
    consumer_before: "소비자가(KRW)",
    recommended_before: "권장판매가(KRW)",
    supply_before: "공급가(KRW)",
    consumer_after: "소비자가(KRW).1",
    recommended_after: "권장판매가(KRW).1",
    supply_after: "공급가(KRW).1",
  },
  en: {
    sim_type: "SIm type",
    update_type: "Update Type",
    vendor_code: "Vendor Code",
    plan_name: "Plan Name",
    days: "Days",
    days_fix: "days",
    allowance: "Data",
    option_name: "Option Name",
    option_api_id: "Option Name(API)",
    carrier: "Carrier",
    data_class: "Data.1",
    network: "Network",
    internet: "Internet",
    qos: "QOS",
    validity: "Validity Period",
    apn: "APN",
    install_benchmark: "LoginBenchmark",
    kyc: "KYC",
    hotspot: "Hotspot",
    activation_policy: "Activation Policy",
    mcc: "MCC",
    mnc: "MNC",
    esim: "eSIM",
    usim: "USIM",
    request_shipment: "Request\n (shipment)",
    request_shipment_alt: "Request\n(shipment)",
    status_check: "Status check\n (Install / usage etc.)",
    status_check_alt: "Status check\n(Install  / usage etc.)",
    extension: "Extension\n(Same ICCID)",
    consumer_before: "Normal Price(KRW)",
    recommended_before: "Recommended Price(KRW)",
    supply_before: "Supply Price(KRW)",
    consumer_after: "Normal Price(KRW).1",
    recommended_after: "Recommended Price(KRW).1",
    supply_after: "Supply Price(KRW).1",
  },
} as const;

export type BongsimExcelCanonicalKey = keyof typeof BONGSIM_EXCEL_COLUMN_MAP.ko;
