/**
 * 이미지 출처(source_type / source_note / is_generated) 운영 규칙.
 * 공개 SEO 텍스트는 file_name/alt/page context를 사용하고, source_type은 내부 관리 메타로만 쓴다.
 */

export const IMAGE_SOURCE_TYPES = [
  'pexels',
  'gemini_auto',
  'gemini_manual',
  'photo_owned',
  'istock',
] as const

export type ImageSourceType = (typeof IMAGE_SOURCE_TYPES)[number]
export type ImageSourceName = 'Pexels' | 'Gemini Auto' | 'Gemini Manual' | 'Owned Photo' | 'iStock'

const ALLOWED_SET = new Set<string>(IMAGE_SOURCE_TYPES)

function baseName(fileName: string): string {
  return String(fileName ?? '').replace(/^.*[/\\]/, '').trim()
}

export function isAllowedImageSourceType(s: string): s is ImageSourceType {
  return ALLOWED_SET.has(s)
}

export function allowedImageSourceTypesList(): string {
  return IMAGE_SOURCE_TYPES.join(', ')
}

/**
 * 파일명 `iStock-` prefix 규칙(대소문자 무시) 자동 판정.
 * - 원본이 경로를 포함해도 basename 기준으로 판정.
 */
export function detectImageSourceTypeFromFilename(fileName: string): ImageSourceType | null {
  const base = baseName(fileName)
  if (!base) return null
  return base.toLowerCase().startsWith('istock-') ? 'istock' : null
}

/**
 * source_type 해석 규칙:
 * 1) 자동 수집 파이프라인 플래그 우선 (`pexels`, `gemini_auto`)
 * 2) 수동 업로드에서 파일명 iStock- 접두면 무조건 `istock`
 * 3) 그 외 명시값 사용
 * 4) 수동 업로드 기본값은 `photo_owned`
 */
export function resolveImageSourceType(params: {
  isManualUpload: boolean
  explicitSourceType?: ImageSourceType | null
  originalFileName?: string | null
  isGeminiAuto?: boolean
  isPexelsAuto?: boolean
}): ImageSourceType {
  if (params.isPexelsAuto) return 'pexels'
  if (params.isGeminiAuto) return 'gemini_auto'

  const byName = detectImageSourceTypeFromFilename(params.originalFileName ?? '')
  if (params.isManualUpload && byName === 'istock') return 'istock'

  if (params.explicitSourceType) return params.explicitSourceType
  return params.isManualUpload ? 'photo_owned' : 'pexels'
}

export function isGeneratedImageSourceType(sourceType: ImageSourceType): boolean {
  return sourceType === 'gemini_auto' || sourceType === 'gemini_manual'
}

export function sourceTypeToSourceName(sourceType: ImageSourceType): ImageSourceName {
  switch (sourceType) {
    case 'pexels':
      return 'Pexels'
    case 'gemini_auto':
      return 'Gemini Auto'
    case 'gemini_manual':
      return 'Gemini Manual'
    case 'photo_owned':
      return 'Owned Photo'
    case 'istock':
      return 'iStock'
  }
}

/** alias: 테스트/호출부 의미를 명확히 하기 위한 이름 */
export function resolveImageSourceName(sourceType: ImageSourceType): ImageSourceName {
  return sourceTypeToSourceName(sourceType)
}

/**
 * 명시 source_type(raw) 파싱. 빈 문자열은 undefined.
 * @throws Error 메시지에 Invalid source_type 포함
 */
export function parseOptionalImageSourceType(explicitRaw: string | null | undefined): ImageSourceType | undefined {
  const t = String(explicitRaw ?? '').trim()
  if (!t) return undefined
  if (!isAllowedImageSourceType(t)) {
    throw new Error(`Invalid source_type. Allowed: ${allowedImageSourceTypesList()}`)
  }
  return t
}

export function buildDefaultSourceNote(sourceType: ImageSourceType): string {
  const map: Record<ImageSourceType, string> = {
    pexels: 'admin auto collected pexels',
    gemini_auto: 'admin auto generated gemini',
    gemini_manual: 'manual upload generated by gemini',
    photo_owned: 'manual upload owned photo',
    istock: 'manual upload detected istock prefix',
  }
  return map[sourceType]
}

export function resolveImageAssetSource(input: {
  originalFileName: string
  explicitSourceTypeRaw?: string | null
  explicitSourceNoteRaw?: string | null
  isManualUpload?: boolean
  isGeminiAuto?: boolean
  isPexelsAuto?: boolean
}): { sourceType: ImageSourceType; sourceName: ImageSourceName; sourceNote: string; isGenerated: boolean } {
  const explicit = parseOptionalImageSourceType(input.explicitSourceTypeRaw)
  const sourceType = resolveImageSourceType({
    isManualUpload: input.isManualUpload !== false,
    explicitSourceType: explicit ?? null,
    originalFileName: input.originalFileName,
    isGeminiAuto: input.isGeminiAuto,
    isPexelsAuto: input.isPexelsAuto,
  })
  const noteTrim = String(input.explicitSourceNoteRaw ?? '').trim()
  return {
    sourceType,
    sourceName: sourceTypeToSourceName(sourceType),
    sourceNote: noteTrim || buildDefaultSourceNote(sourceType),
    isGenerated: isGeneratedImageSourceType(sourceType),
  }
}
