/**
 * 등록 일정 imageKeyword — 한글 routeText·본문 → 영문 POI/도시 (전 공급사 공용 SSOT).
 * 공급사별 지역 ROI 테이블 금지 — 이 파일 + lib/pexels-keyword.ts POI_KO_TO_EN 만 사용.
 * REGRESSION-FREEZE[schedule-poi-regex-ssot]: 공급사 모듈에 POI/CITY regex 중복 금지 — manifest
 * REGRESSION-FREEZE[schedule-segment-poi-oceania-japan-europe]: NZ·AU·일본·유럽·북유럽·발트·이탈리아·노르망디·장가계·남미 routeText — manifest
 */
import { finalizeScheduleImageKeyword } from '@/lib/pexels-place-name-keyword'
import { mapDestination, mapKoreanPoiSegment, normalizeSemanticPoiKey } from '@/lib/pexels-keyword'

export type SchedulePoiRegexRule = { re: RegExp; en: string }

export const SCHEDULE_SPOT_KO_REGEX_RULES: ReadonlyArray<{ re: RegExp; en: string }> = [
  { re: /내원교/u, en: "Japanese Covered Bridge" },
  { re: /호이안\s*고대\s*도시|호이안\s*올드\s*타운|호이안\s*고성/u, en: "Hoi An Ancient Town" },
  { re: /^호이안$/u, en: "Hoi An Ancient Town" },
  { re: /영흥사|손짜/u, en: "Linh Ung Pagoda" },
  { re: /다낭\s*대성당/u, en: "Da Nang Cathedral" },
  { re: /미케\s*비치/u, en: "My Khe Beach" },
  { re: /천주교당|성미카엘/u, en: "St Michael's Cathedral" },
  { re: /잔교/u, en: "Zhanqiao Pier" },
  { re: /54광장|5\.4광장/u, en: "May Fourth Square" },
  { re: /팔대관|八大关/u, en: "Badaguan Scenic Area Qingdao" },
  { re: /맥주\s*박물관|Tsingtao\s*Beer/i, en: "Tsingtao Beer Museum Qingdao" },
  { re: /대복도|따빠오|Taipingdao|Small\s*Qingdao/i, en: "Small Qingdao Island Qingdao" },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: 백장협≠Bailong · 백룡=Elevator · cable car 보조어 금지 — manifest
  { re: /천자산|Tianzi\s*Mountain/i, en: 'Tianzi Mountain' },
  { re: /천문산|Tianmen\s*Mountain|天門山/u, en: 'Tianmen Mountain' },
  { re: /백장협|Baizhang(?:xia)?|Baizhang\s*Gorge/i, en: 'Baizhang Gorge' },
  { re: /백룡\s*(?:엘리베이터|엘리베|승강기)?|Bailong\s*Elevator|百龍/i, en: 'Bailong Elevator' },
  { re: /유리\s*교|Glass\s*Bridge|玻璃桥/i, en: 'Zhangjiajie Glass Bridge' },
  { re: /보봉탑|원가계|어필봉|Avatar\s*Hallelujah|아바타/i, en: 'Avatar Hallelujah Mountain' },
  { re: /십리\s*화랑|十里画廊|Ten\s*Mile\s*Gallery|Shili\s*Gallery/i, en: 'Ten Mile Gallery' },
  { re: /보봉호|宝峰湖|Baofeng\s*Lake/i, en: 'Baofeng Lake' },
  { re: /금편계곡|Golden\s*Whip/i, en: 'Golden Whip Stream' },
  { re: /황룡\s*동굴|Yellow\s*Dragon\s*Cave|黄龙洞/u, en: 'Yellow Dragon Cave' },
  { re: /황石寨|黄石寨|Huangshi\s*Village|黄石/u, en: 'Huangshi Village' },
  { re: /미혼대/i, en: 'Avatar Mountain' },
  { re: /천하일랑|천하제일교/i, en: 'First Bridge Under Heaven' },
  { re: /하룡공원|Helong\s*Park/i, en: 'Helong Park' },
  { re: /칠성산|Seven\s*Star/i, en: 'Seven Star Mountain' },
  { re: /72\s*기루|七十二奇楼/u, en: 'Zhangjiajie 72 Qilou' },
  { re: /장가계|Zhangjiajie|張家界/u, en: 'Zhangjiajie National Forest Park' },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: 북경 자금성·경산·천안문 — 도시허브≠자금성 — manifest
  { re: /자금성|紫禁城|Forbidden\s*City/i, en: 'Forbidden City' },
  { re: /경산\s*공원|Jingshan\s*Park/i, en: 'Jingshan Park' },
  { re: /팔달령|만리장성|Great\s*Wall/i, en: 'Great Wall of China' },
  { re: /명\s*13\s*릉|명십삼릉|Ming\s*Tombs/i, en: 'Ming Tombs Beijing' },
  { re: /이화원|Summer\s*Palace/i, en: 'Summer Palace' },
  { re: /천안문|Tiananmen/i, en: 'Tiananmen Square' },
  { re: /스차하이|십찰해|什刹海|Shichahai/i, en: 'Shichahai' },
  { re: /올림픽\s*경기장|새둥지|Bird'?s?\s*Nest|국가체육장/i, en: 'Beijing National Stadium' },
  { re: /더\s*플레이스|The\s*Place/i, en: 'The Place Beijing' },
  { re: /파르테논|Parthenon/i, en: "Parthenon Athens Acropolis" },
  { re: /프로필레아|Propylaea|PROPYLAIA/i, en: "Propylaea Athens Acropolis" },
  { re: /에렉티온|Erechtheion/i, en: "Erechtheion Athens Acropolis" },
  { re: /니케\s*신전|Temple\s*of\s*Athena\s*Nike/i, en: "Temple of Athena Nike Athens" },
  { re: /이아\s*마을|^이아$|Oia/i, en: "Oia Santorini blue domes" },
  { re: /피라\s*마을|^피라$|\bFira\b/i, en: "Fira Santorini caldera" },
  { re: /피로스테파니|Firostefani/i, en: "Firostefani Santorini village" },
  { re: /이메로비글리|이메비글리|Imerovigli/i, en: "Imerovigli Santorini caldera" },
  { re: /플라카|Plaka/i, en: "Plaka Athens neighborhood" },
  { re: /델파이|Delphi/i, en: "Delphi Greece ancient ruins" },
  { re: /메테오라|Meteora/i, en: "Meteora monasteries Greece" },
  { re: /산토리니|Santorini/i, en: "Santorini caldera blue domes" },
  { re: /아크로티리|Akrotiri/i, en: "Akrotiri archaeological site Santorini" },
  { re: /아무디|Amoudi/i, en: "Amoudi Bay Santorini fishing harbor" },
  { re: /아크로(?:폴리스|폴)|Acropolis/i, en: "Acropolis Athens Parthenon" },
  { re: /아라호바|Arachova/i, en: "Arachova Greece mountain village" },
  { re: /모나스티라키|Monastiraki/i, en: "Monastiraki Athens flea market" },
  { re: /고대\s*코린트|Ancient\s*Corinth|코린트\s*\(?Corinth/i, en: "Ancient Corinth ruins Greece" },
  { re: /나프플리온|Nafplio/i, en: "Nafplio Greece harbor fortress" },
  { re: /팔라미디|Palamidi/i, en: "Palamidi Fortress Nafplio" },
  { re: /차크리|Grand\s*Palace|왕궁.*에메랄드|에메랄드\s*사원/i, en: "Grand Palace Bangkok" },
  { re: /황금\s*절벽|왓\s*카오/i, en: "Wat Arun Bangkok" },
  { re: /진리의\s*성전|Sanctuary\s*of\s*Truth/i, en: "Sanctuary of Truth Pattaya" },
  { re: /농눅|Nong\s*Nooch/i, en: "Nong Nooch Tropical Garden Pattaya" },
  { re: /아시아티크|Asiatique/i, en: "Asiatique Bangkok night market" },
  { re: /니모섬|Nemo\s*Island/i, en: "Koh Nang Yuan snorkeling Thailand" },
  { re: /하쿠토\s*신사|Hakuto/i, en: "Hakuto Shrine Tottori" },
  { re: /유시엔|Yuushien|유후인/i, en: "Yuushien Garden Shimane" },
  { re: /테살로니키|Thessaloniki/i, en: "White Tower Thessaloniki" },
  { re: /세렝게티|Serengeti/i, en: "Serengeti savanna wildlife" },
  { re: /빅토리아\s*폭포|Victoria\s*Falls/i, en: "Victoria Falls waterfall panorama" },
  { re: /이과수|Iguazu/i, en: "Iguazu Falls waterfall panorama" },
  { re: /올림픽\s*요트|요트\s*경기장/u, en: "Qingdao Olympic Sailing Center" },
  { re: /지모루|찌모루/u, en: "Jimo Road Market" },
  { re: /죠잔케이|Jozankei|定山渓/u, en: "Jozankei" },
  { re: /오쿠라야마|Okurayama/i, en: "Okurayama Ski Jump Stadium" },
  { re: /미츠이\s*아울렛|Mitsui\s*Outlet/i, en: "Mitsui Outlet Park Sapporo" },
  { re: /후라노\s*와인|Furano\s*Wine/i, en: "Furano Wine House" },
  { re: /팜\s*(?:도|토)미타|Farm\s*Tomita/i, en: "Farm Tomita Furano" },
  { re: /시키사이노오카|Shikisai/i, en: "Shikisai-no-Oka Biei" },
  { re: /(?:청의\s*호수|아오이케|Blue\s*Pond)/i, en: "Blue Pond Biei" },
  { re: /은하폭포|Ginga\s*Falls/i, en: "Ginga Falls Sounkyo" },
  { re: /유성폭포|Ryusei\s*Falls/i, en: "Ryusei Falls Sounkyo" },
  { re: /기타이치|Kitaichi/i, en: "Kitaichi Glass Otaru" },
  { re: /시로이\s*코이비토|Shiroi\s*Koibito/i, en: "Shiroi Koibito Park" },
  { re: /삿포로\s*시계탑|Sapporo\s*Clock/i, en: "Sapporo Clock Tower" },
  { re: /^후라노$/u, en: "Farm Tomita Furano" },
  { re: /^비에이$/u, en: "Shikisai-no-Oka Biei" },
  { re: /^소운쿄$/u, en: "Sounkyo Gorge" },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: 치토세 공항·후라노 라벤더 — Provence 환각 금지 — manifest
  { re: /치토세\s*(?:국제)?\s*공항|New\s*Chitose|CTS/i, en: "New Chitose Airport Hokkaido" },
  { re: /^치토세$/u, en: "New Chitose Airport Hokkaido" },
  { re: /(?:후라노|비에이|홋카이도|Hokkaido|Furano|Biei).{0,40}라벤더|라벤더.{0,40}(?:후라노|비에이|홋카이도|Farm\s*Tomita)|라벤더\s*소프트/i, en: "Farm Tomita Furano lavender" },
  { re: /노보리베츠.*지옥|지옥\s*계곡|Jigokudani/u, en: "Noboribetsu Jigokudani" },
  { re: /오타루\s*운하|Otaru\s*Canal/u, en: "Otaru Canal" },
  { re: /오르골|Music\s*Box/u, en: "Otaru Music Box Museum" },
  { re: /오도리\s*공원|Odori\s*Park/u, en: "Odori Park" },
  { re: /도야\s*호수|Lake\s*Toya/u, en: "Lake Toya" },
  { re: /소호\s*거리|SoHo(?!\s*Hong)/iu, en: "SoHo Hong Kong" },
  { re: /타이쿤|Tai\s*Kwun/u, en: "Tai Kwun" },
  { re: /헐리우드\s*로드|Hollywood\s*Road/u, en: "Hollywood Road Hong Kong" },
  { re: /미드[-\s]*레벨\s*에스컬레이터|Mid[-\s]*level\s*Escalator/u, en: "Mid-Levels Escalator" },
  { re: /리퉁\s*애비뉴|Li\s*Yuen|L\.?\s*Yuen/i, en: "Li Yuen Street Hong Kong" },
  { re: /블루\s*하우스|Blue\s*House/u, en: "Blue House Hong Kong" },
  { re: /빅토리아\s*피크|Victoria\s*Peak/u, en: "Victoria Peak" },
  { re: /피크\s*트램|Peak\s*Tram/u, en: "Peak Tram" },
  { re: /웡타이신|Wong\s*Tai\s*Sin/u, en: "Wong Tai Sin Temple" },
  { re: /성\s*바울\s*성당|Ruins\s*of\s*St\.?\s*Paul|St\.?\s*Paul'?s?/iu, en: "Ruins of St. Paul's" },
  { re: /세나두\s*광장|Senado\s*Square/u, en: "Senado Square" },
  { re: /침사추이\s*해변|연인의\s*거리|스타의\s*거리|Avenue\s*of\s*Stars/u, en: "Avenue of Stars Hong Kong" },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: 튀르키예 명소 — skyline·interior 보조어 금지 — manifest
  { re: /술탄\s*아흐메트|블루\s*모스크|Sultan\s*Ahmed/i, en: "Sultan Ahmed Mosque Istanbul" },
  { re: /그랜드\s*바자르|Grand\s*Bazaar/i, en: "Grand Bazaar Istanbul" },
  { re: /지하\s*물\s*궁전|지하물궁전|Basilica\s*Cistern/i, en: "Basilica Cistern Istanbul" },
  { re: /돌마바흐체|Dolmabahce|Dolmabahçe/i, en: "Dolmabahce Palace Istanbul" },
  { re: /투즈괼|소금\s*호수|Lake\s*Tuz/i, en: "Lake Tuz Turkey" },
  { re: /데린쿠유|지하\s*도시|Derinkuyu/i, en: "Derinkuyu Underground City Cappadocia" },
  { re: /괴레메|Goreme|Göreme/i, en: "Goreme Cappadocia Fairy Chimneys" },
  { re: /우치히사르|Uchisar/i, en: "Uchisar Castle Cappadocia" },
  { re: /데브란트|Devrent/i, en: "Devrent Valley Cappadocia" },
  { re: /카파도키아|카파토키아|Cappadocia/i, en: "Cappadocia Fairy Chimneys" },
  { re: /오브룩|Obruk/i, en: "Obruk Lake Turkey" },
  { re: /이블리\s*미나레|Yivli\s*Minaret/i, en: "Yivli Minaret Antalya" },
  { re: /하드리아누스|Hadrian/i, en: "Hadrian's Gate Antalya" },
  { re: /올림포스|Olympos|Olympus/i, en: "Mount Olympos Antalya" },
  { re: /히에라폴리스|Hierapolis/i, en: "Hierapolis Pamukkale" },
  { re: /석회붕|파묵칼레|Pamukkale/i, en: "Pamukkale Travertine Terraces" },
  { re: /쉬린제|Sirince|Şirince/i, en: "Sirince Village" },
  { re: /에페소|Efes|Ephesus/i, en: "Ephesus Library of Celsus" },
  { re: /에페수스|Ephesus/i, en: "Ephesus Library of Celsus" },
  { re: /(부르사|Bursa)/i, en: "Green Tomb Bursa" },
  { re: /성\s*소피아|아야\s*소피아|Hagia\s*Sophia/i, en: "Hagia Sophia Istanbul" },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: 단독「역사 박물관」≠ Istanbul — 이스탄불 문맥 필수 — manifest
  {
    re: /(?:이스탄불|Istanbul).{0,48}(?:역사\s*박물관|Archaeological\s*Museum)|(?:역사\s*박물관|Archaeological\s*Museum).{0,48}(?:이스탄불|Istanbul)/i,
    en: "Istanbul Archaeological Museum",
  },
  { re: /톱카프|Topkapi|Topkapı/i, en: "Topkapi Palace Istanbul" },
  { re: /발랏|Balat/i, en: "Balat Istanbul" },
  { re: /보스포러스|Bosphorus|Bosporus/i, en: "Bosphorus Strait Istanbul" },
  { re: /피엘로티|Pierre\s*Loti/i, en: "Pierre Loti Hill Istanbul" },
  { re: /포나가(?:\s*참)?(?:\s*사원)?|포나가르|Po Nagar|Cham Towers/i, en: "Po Nagar Cham Towers" },
  { re: /달랏\s*꽃\s*정원|Dalat Flower|Da Lat Flower/i, en: "Da Lat Flower Garden Vietnam" },
  { re: /달랏|Da Lat|Dalat/i, en: "Da Lat Vietnam highland city" },
  { re: /나트랑|Nha Trang/i, en: "Nha Trang beach Vietnam" },
  { re: /(?:유|우)원|豫园|예원/u, en: "Yu Garden Shanghai" },
  { re: /외탄|外灘|外滩|와탄/u, en: "Shanghai Bund skyline" },
  { re: /항주|杭州|西湖/u, en: "West Lake Hangzhou" },
  { re: /송성|宋城|송가무|가무쇼/u, en: "Songcheng Park Hangzhou" },
  { re: /청황|城隍/u, en: "City God Temple of Shanghai" },
  { re: /동방명주|东方明珠/u, en: "Oriental Pearl Tower Shanghai" },
  { re: /주가각|朱家角/u, en: "Zhujiajiao water town canal bridge" },
  { re: /우캉\s*루|武康路/u, en: "Wukang Road Shanghai" },
  { re: /남경\s*로|南京路/u, en: "Nanjing Road Shanghai" },
  { re: /에펠\s*탑|에펠탑|Eiffel/i, en: "Eiffel Tower Paris" },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: 도게츠교≠Doge's Palace — manifest
  { re: /도게츠(?:교)?|渡月橋|Togetsu(?:kyo)?/i, en: "Togetsukyo Bridge Arashiyama Kyoto" },
  { re: /아라시야마|嵐山|Arashiyama/i, en: "Arashiyama bamboo grove Kyoto" },
  { re: /치쿠린|竹林|Bamboo\s*Grove/i, en: "Arashiyama bamboo grove Kyoto" },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: 교토·오사카 Kansai POI — Day2/3 dup·Day4 Arashiyama bleed — manifest
  { re: /기요미즈(?:데라|사)?|청수사|清水寺|Kiyomizu/i, en: "Kiyomizu-dera" },
  { re: /니넨자카|이년坂|Ninen(?:zaka)?/i, en: "Ninen-zaka Kyoto" },
  { re: /산넨자카|三年坂|Sannen(?:zaka)?/i, en: "Sannen-zaka Kyoto" },
  { re: /니시키\s*(?:재래)?시장|錦市場|Nishiki/i, en: "Nishiki Market Kyoto" },
  { re: /노노미야\s*신사|野宮神社|Nonomiya/i, en: "Nonomiya Shrine Kyoto" },
  { re: /호센인|宝泉院|Hosen(?:-?in)?/i, en: "Hosen-in Ohara Kyoto" },
  { re: /비와호(?:대교)?|琵琶湖|Lake\s*Biwa|Biwa/i, en: "Lake Biwa Japan" },
  { re: /오미하치만|近江八幡|Omihachiman|Omi\s*Hachiman/i, en: "Omihachiman canal Japan" },
  { re: /하치만보리|八幡堀/i, en: "Hachimanbori canal Omihachiman" },
  { re: /하치만야마|八幡山/i, en: "Hachimanayama ropeway Omihachiman" },
  { re: /신사이바시|心斎橋|Shinsaibashi/i, en: "Shinsaibashi Osaka" },
  { re: /후시미\s*이나리|Fushimi\s*Inari/i, en: "Fushimi Inari shrine Kyoto" },
  { re: /도칼레|도게(?:의)?\s*궁|Doge'?s?\s*Palace|Palazzo\s*Ducale/i, en: "Doge's Palace Venice" },
  { re: /룬달레|Rundale/i, en: "Rundale Palace Latvia Baroque gardens" },
  { re: /블랙\s*헤드|Black\s*Heads?/i, en: "House of Blackheads Riga" },
  { re: /아르\s*누보|Art\s*Nouveau/i, en: "Riga Art Nouveau district" },
  { re: /리가\s*성당|Riga\s*Cathedral/i, en: "Riga Cathedral Latvia" },
  { re: /게이트\s*오브\s*던|Gates\s*of\s*Dawn/i, en: "Gates of Dawn Vilnius" },
  { re: /트라카이|Trakai/i, en: "Trakai Island Castle Lithuania" },
  { re: /수오멘린나|Suomenlinna/i, en: "Suomenlinna Helsinki sea fortress" },
  { re: /비[르겔]+란|Vigeland/i, en: "Vigeland Sculpture Park Oslo" },
  { re: /아[케크][르]*후스|Akershus/i, en: "Akershus Fortress Oslo" },
  { re: /플롬|Flåm|Flam/i, en: "Flam Norway fjord railway" },
  { re: /게이랑|Geiranger/i, en: "Geirangerfjord Norway waterfall" },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: 북유럽 ENP121 — Preikestolen·십자가언덕·레르달 — manifest
  { re: /프레이케스톨(?:렌|론)|Preikestolen|Pulpit\s*Rock/i, en: "Preikestolen Pulpit Rock Norway" },
  { re: /십자가(?:의)?\s*언덕|Hill\s*of\s*Crosses/i, en: "Hill of Crosses Lithuania" },
  { re: /요정의\s*길|Trolltunga/i, en: "Trolltunga Norway cliff" },
  { re: /비올리|Voss(?![a-z])/i, en: "Voss Norway fjord village" },
  { re: /(?:레르달|라르달)|L[æae]rdal/i, en: "Laerdal Norway Fjord" },
  { re: /헤우게순|Haugesund/i, en: "Haugesund Norway harbor" },
  { re: /스타방에르|Stavanger/i, en: "Stavanger Norway harbor" },
  { re: /피얼란드\s*빙하|Fj[æae]rland/i, en: "Fjaerland Glacier Museum Norway" },
  { re: /골든\s*루트|Golden\s*Route/i, en: "Norway Golden Route fjord scenic" },
  { re: /나에로이|N[æae]r[øoy]fjord|네로이|내로이/i, en: "Naeroyfjord Norway UNESCO fjord" },
  { re: /세븐\s*시스터|Seven\s*Sisters/i, en: "Seven Sisters waterfall Geirangerfjord Norway" },
  { re: /스타이어|Storfjord|스토르피ord/i, en: "Storfjord Norway cruise scenic" },
  { re: /오슬로\s*오페라|Oslo\s*Opera/i, en: "Oslo Opera House Norway harbor" },
  { re: /플렌티|Piazzale\s*Michelangelo|피렌체\s*전망대/i, en: "Piazzale Michelangelo Florence view" },
  { re: /브뤼겐|Bryggen/i, en: "Bergen Bryggen wooden wharf Norway" },
  { re: /뉘하운|Nyhavn/i, en: "Copenhagen Nyhavn colorful canal houses" },
  { re: /아말리엔보르|Amalienborg/i, en: "Copenhagen Amalienborg Palace square" },
  { re: /인어\s*공주|Little\s*Mermaid/i, en: "Copenhagen Little Mermaid statue" },
  { re: /바사\s*(?:박물관|호|박물관)?|Vasa(?:\s*Museum)?/i, en: "Stockholm Vasa Museum ship" },
  { re: /감라스탄|Gamla\s*Stan/i, en: "Stockholm Gamla Stan old town" },
  { re: /(?:스웨덴|스톡홀름)\s*왕궁|Stockholm\s*Royal\s*Palace/i, en: "Stockholm Royal Palace" },
  { re: /스톡홀름\s*시청|Stockholm\s*City\s*Hall/i, en: "Stockholm City Hall" },
  { re: /토베리\s*광장|Senate\s*Square/i, en: "Helsinki Senate Square cathedral" },
  { re: /(?:토목파에|톰페아|톰페아\s*언덕|톰페아\s*성)|Toompea/i, en: "Toompea Castle Tallinn Estonia" },
  { re: /왕궁\s*광장|Royal\s*Castle(?=.*(?:바르샤바|Warsaw))/i, en: "Warsaw Royal Castle square" },
  { re: /트레비|Trevi/i, en: "Trevi Fountain Rome" },
  { re: /스페인\s*계단|Spanish\s*Steps/i, en: "Spanish Steps Rome" },
  { re: /포로\s*로마노|Roman\s*Forum/i, en: "Roman Forum Rome" },
  { re: /응고롱고로|Ngorongoro/i, en: "Ngorongoro Crater Tanzania wildlife" },
  { re: /아루샤|Arusha/i, en: "Arusha Tanzania Mount Meru gateway" },
  { re: /마니야라|Manyara/i, en: "Lake Manyara Tanzania wildlife" },
  { re: /마사이\s*마라|Masai\s*Mara/i, en: "Masai Mara savanna Kenya" },
  { re: /리빙스턴|Livingstone/i, en: "Victoria Falls Livingstone Zambia" },
  { re: /케이프타운|Cape\s*Town|CAPETOWN/i, en: "Cape Town Table Mountain South Africa" },
  { re: /테이블\s*마운틴|Table\s*Mountain/i, en: "Table Mountain Cape Town" },
  { re: /V\s*&\s*A\s*Waterfront|워터프론트/i, en: "V&A Waterfront Cape Town harbor" },
  { re: /마나도|Manado/i, en: "Manado Sulawesi Indonesia coastal city" },
  { re: /부나켄|Bunaken/i, en: "Bunaken National Marine Park Indonesia" },
  { re: /실라덴|Siladen/i, en: "Siladen Island Bunaken diving Indonesia" },
  { re: /통코|Tangkoko/i, en: "Tangkoko Nature Reserve Sulawesi Indonesia" },
  { re: /토모혼|Tomohon/i, en: "Tomohon colorful market Sulawesi Indonesia" },
  { re: /코파카바나|Copacabana/i, en: "Copacabana Beach Rio de Janeiro" },
  { re: /슈가\s*로프|Sugar\s*Loaf|Pão\s*de\s*Açúcar/i, en: "Sugar Loaf Mountain Rio de Janeiro cable car" },
  { re: /셀라론|Selarón|Escadaria/i, en: "Selaron Steps Rio de Janeiro colorful stairs" },
  { re: /멕시코\s*시티|Mexico\s*City/i, en: "Mexico City Zocalo cathedral square" },
  { re: /소칼로|Z[oó]calo/i, en: "Mexico City Zocalo cathedral square" },
  { re: /테오티와칸|Teotihuacan/i, en: "Teotihuacan pyramids Mexico ancient ruins" },
  { re: /톨란톤고|Tolantongo/i, en: "Tolantongo hot springs canyon Mexico" },
  { re: /과달루페|Guadalupe\s*Basilica|Basilica\s*de\s*Guadalupe/i, en: "Basilica of Guadalupe Mexico City" },
  { re: /달\s*골|Valle\s*de\s*la\s*Luna|Moon\s*Valley/i, en: "Valle de la Luna La Paz Bolivia moon landscape" },
  { re: /라\s*파스|La\s*Paz/i, en: "La Paz Bolivia cable car city view" },
  { re: /상하이\s*디즈니|Shanghai\s*Disney/i, en: "Shanghai Disneyland castle" },
  { re: /베른|Bern/i, en: "Bern Switzerland Zytglogge clock tower" },
  { re: /죄수의\s*탑|Zytglogge/i, en: "Bern Zytglogge clock tower" },
  { re: /모나코|Monaco/i, en: "Monaco Monte Carlo harbor" },
  { re: /몬테\s*카를로|Monte\s*Carlo/i, en: "Monte Carlo Casino Monaco" },
  { re: /모나코\s*대성당|Monaco\s*Cathedral|Saint\s*Nicholas\s*Cathedral/i, en: "Monaco Cathedral old town" },
  { re: /엑조틱|Exotic\s*Garden|콜?드\s*데\s*la\s*Terre/i, en: "Exotic Garden Monaco cliff cactus" },
  { re: /에즈\s*마을|Eze\s*(?:sur|village|Village)/i, en: "Eze village French Riviera hilltop" },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: 프랑스 일주 명소 — manifest
  { re: /빛의\s*채석장|Carrieres?\s*des\s*Lumieres|Carri[eè]res\s*des\s*Lumi[eè]res/i, en: "Carrieres des Lumieres Provence" },
  { re: /레\s*보(?:\s*드)?\s*프로방스|Les\s*Baux/i, en: "Les Baux de Provence" },
  { re: /생폴드방스|Saint[\s-]*Paul[\s-]*de[\s-]*Vence/i, en: "Saint Paul de Vence" },
  { re: /쉬농소\s*성?|Chenonceau/i, en: "Chenonceau Castle Loire" },
  { re: /앙부(?:와즈)?\s*성?|Amboise/i, en: "Chateau d Amboise Loire" },
  { re: /루아르\s*고성|Loire\s*(?:Valley\s*)?castles?/i, en: "Chenonceau Castle Loire" },
  { re: /생테밀리옹|Saint[\s-]*Emilion|St\.?\s*Emilion/i, en: "Saint Emilion Village" },
  { re: /아비뇽\s*구시가|교황청|Palais\s*des\s*Papes|Avignon/i, en: "Palace of the Popes Avignon" },
  { re: /고대\s*극장|Orange\s*(?:Ancient|Roman)\s*Theatre/i, en: "Orange Ancient Roman Theatre Provence" },
  { re: /카르카손|Carcassonne/i, en: "Carcassonne Castle" },
  { re: /보르도\s*부르스|Place\s*de\s*la\s*Bourse|피에르\s*다리/i, en: "Place de la Bourse Bordeaux" },
  { re: /프롬나드\s*데\s*장글래|Promenade\s*des\s*Anglais/i, en: "Promenade des Anglais Nice" },
  // 「베니스」 substring 「니스」 오매칭 금지 — 단독 니스·영문 Nice만
  { re: /니스\s*해변|니스\s*구시가|(?:^|[\s\-·,/])니스(?:$|[\s\-·,/])|\bNice\b(?:\s*Beach)?/i, en: "Promenade des Anglais Nice Beach" },
  { re: /샤갈\s*미술관|Chagall/i, en: "Chagall Museum Nice" },
  { re: /사보나|Savona/i, en: "Savona Liguria harbor" },
  { re: /미라보\s*광장|코르(?:스|트)\s*미라보|Cours\s*Mirabeau/i, en: "Cours Mirabeau Aix-en-Provence" },
  { re: /미라보|Mirabeau/i, en: "Cours Mirabeau Aix-en-Provence" },
  { re: /Aix|엑스\s*프로방스|Aix-en-Provence/i, en: "Aix-en-Provence old town fountain" },
  {
    re: /오슬로[\s\S]{0,160}(?:유람선|GO\s*NORDIC|CRUISELINE)|(?:유람선|GO\s*NORDIC)[\s\S]{0,80}오슬로/i,
    en: 'Akershus Fortress Oslo',
  },
  { re: /코펜하겐\s*출발/i, en: 'Copenhagen Amalienborg Palace square' },
  { re: /바르샤바\s*출발/i, en: 'Warsaw Royal Castle square' },
  { re: /노르웨이\s*피요르드|Oslo\s*fjord|유람선\s*크루즈|GO\s*NORDIC/i, en: "Oslo fjord sightseeing cruise Norway" },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: 이집트 스핑크스 ≠ Jungfraujoch — manifest
  {
    re: /스핑크스\s*전망대|Sphinx\s*Observatory|(?:융프라우|Jungfrau)[\s\S]{0,24}스핑크스|스핑크스[\s\S]{0,24}(?:융프라우|Jungfrau)/i,
    en: 'Jungfraujoch Sphinx Observatory Swiss Alps',
  },
  {
    re: /(?:기자|Giza|피라미드)[\s\S]{0,40}스핑크스|스핑크스[\s\S]{0,40}(?:기자|Giza|피라미드)|Great\s*Sphinx|(?:^|[\s\-·,/])스핑크스(?:$|[\s\-·,/])|\bSphinx\b/i,
    en: 'Great Sphinx of Giza',
  },
  { re: /개선문/u, en: "Arc de Triomphe Paris" },
  { re: /몽생미셸|Mont\s*Saint\s*Michel/i, en: "Mont Saint Michel abbey" },
  { re: /오르세\s*미술관|Orsay/i, en: "Musee d Orsay Paris" },
  { re: /샹젤리제|Champs[\s-]*Elysees/i, en: "Champs Elysees Paris" },
  { re: /시부야|渋谷/u, en: "Shibuya crossing Tokyo night" },
  { re: /하라주쿠|原宿/u, en: "Harajuku Takeshita street Tokyo" },
  { re: /금각사|金閣寺/u, en: "Kinkakuji golden pavilion Kyoto" },
  { re: /은각사|銀閣寺/u, en: "Ginkakuji temple Kyoto" },
  { re: /후시미\s*이나리|伏見稲荷/u, en: "Fushimi Inari Shrine / thousand vermilion torii gates / eye-level front view" },
  { re: /도톤보리|道頓堀/u, en: "Dotonbori Osaka night" },
  // REGRESSION-FREEZE[schedule-segment-poi-us-west]: LA Universal before Japan default — manifest
  { re: /(?:로스\s*앤?젤|Los\s*Angeles|할리우드|Hollywood).{0,48}(?:유|우)니버설|(?:유|우)니버설.{0,48}(?:로스|할리우드|Hollywood|LA\b)/iu, en: "Universal Studios Hollywood" },
  { re: /모뉴먼트\s*밸리|Monument\s*Valley/i, en: "Monument Valley" },
  { re: /홀슈\s*밴드|홀스슈\s*밴드|Horseshoe\s*Bend/i, en: "Horseshoe Bend" },
  { re: /앤텔로프\s*캐년|Antelope\s*Canyon/i, en: "Antelope Canyon" },
  { re: /자이언\s*캐년|Zion\s*(?:National\s*)?Park/i, en: "Zion National Park" },
  { re: /브라이스\s*캐년|Bryce\s*Canyon/i, en: "Bryce Canyon" },
  { re: /요세미티|Yosemite/i, en: "Yosemite National Park" },
  { re: /그랜드\s*캐년|Grand\s*Canyon/i, en: "Grand Canyon" },
  // REGRESSION-FREEZE[lottetour-singapore-register-quality]: Singapore USS before Japan Universal catch-all — manifest
  { re: /(?:유|우)니버설\s*스튜디오\s*(?:싱가포르|singapore)|USS\b/iu, en: "Universal Studios Singapore" },
  { re: /가든스\s*(?:바이\s*)?(?:더\s*)?베이|Gardens\s*by\s*the\s*Bay|슈퍼트리|클라우드\s*포레스트|플라워\s*돔/iu, en: "Gardens by the Bay" },
  { re: /머르?라이언|Merlion/iu, en: "Merlion Park" },
  { re: /센토사|Sentosa/iu, en: "Sentosa" },
  { re: /에스플러네이드|Esplanade/iu, en: "Esplanade Singapore" },
  { re: /차이나타운|Chinatown/iu, en: "Chinatown Singapore" },
  { re: /버드\s*파라다이스|Bird\s*Paradise/iu, en: "Bird Paradise Singapore" },
  { re: /마리나\s*베이\s*샌즈|Marina\s*Bay\s*Sands/iu, en: "Marina Bay Sands" },
  { re: /(?:유|우)니버설\s*스튜디오\s*(?:재팬|japan)|USJ/iu, en: "Universal Studios Japan Osaka" },
  // bare 유니버설 → Japan 금지: 일본·오사카·도쿄 맥락 있을 때만 USJ
  { re: /(?:오사카|도쿄|일본|japan|osaka|tokyo|재팬).{0,32}(?:유|우)니버설|(?:유|우)니버설.{0,32}(?:오사카|도쿄|일본|재팬|japan|osaka)/iu, en: "Universal Studios Japan Osaka" },
  { re: /도쿄\s*디즈니|디즈니(?:랜드|씨)/u, en: "Tokyo Disneyland castle" },
  { re: /돗토리\s*사구|Tottori\s*Sand/i, en: "Tottori Sand Dunes" },
  // REGRESSION-FREEZE[lottetour-schedule-plan-info-description]: bare 돗토리·쿠라요시 → 서일본 POI (Fuji 대체) — manifest
  { re: /돗토리|Tottori/i, en: "Tottori Sand Dunes" },
  { re: /쿠라요시|Kurayoshi/i, en: "Kurayoshi white-walled storehouses" },
  { re: /코난\s*박물관|고쇼\s*아오야마|Gosho\s*Aoyama|Manga\s*Factory/i, en: "Gosho Aoyama Manga Factory" },
  { re: /20\s*세기\s*배|나싯코\s*관|20segi/i, en: "Tottori Nashi Pear Museum" },
  { re: /아다치\s*미술관|Adachi\s*Museum/i, en: "Adachi Museum of Art" },
  { re: /마츠에성|마쓰에성|Matsue\s*Castle/i, en: "Matsue Castle" },
  { re: /미즈키\s*시게루|Mizuki\s*Shigeru/i, en: "Mizuki Shigeru Road" },
  { re: /시오미\s*나와테|Shiomi\s*Nawate/i, en: "Shiomi Nawate Samurai Street" },
  { re: /타이페이\s*101|台北\s*101|타이편\s*101/u, en: "Taipei 101 tower night" },
  { re: /지우펀|九份/u, en: "Jiufen old street Taiwan night" },
  { re: /백두산/u, en: "Changbai Mountain scenic view" },
  { re: /이도백하/u, en: "Erdaobaihe river town Changbai" },
  { re: /금강\s*대?\s*협곡/u, en: "Mount Geumgang gorge scenic" },
  { re: /수안\s*후엉|Xuan\s*Huong/i, en: "Xuan Huong Lake Da Lat / pine forest shore / wide angle" },
  { re: /오르비에또|Orvieto/u, en: "Orvieto Cathedral Duomo / hilltop view" },
  { re: /두오모|Duomo|피렌체\s*성당/i, en: "Florence Cathedral Duomo / red dome plaza / front view" },
  { re: /융프라우|Jungfrau/i, en: "Jungfraujoch Swiss Alps / snow peaks / wide angle" },
  { re: /융프라우요희|Jungfraujoch|Sphinx\s*Observatory/i, en: "Jungfraujoch Sphinx Observatory Swiss Alps" },
  { re: /인터라켄|Interlaken/i, en: "Interlaken Swiss Alps / lake view / wide angle" },
  { re: /루체른|Lucerne|Luzern/i, en: "Chapel Bridge Lucerne / lake view / wide angle" },
  { re: /카펠교|Kapellbrücke|Chapel Bridge/i, en: "Chapel Bridge Lucerne / lake view" },
  { re: /빈사의\s*사자|Lion Monument/i, en: "Lion Monument Lucerne / rock carving" },
  { re: /^피사$/u, en: "Leaning Tower of Pisa cathedral square" },
  { re: /피사\s*대성당|Pisa\s*Cathedral/i, en: "Pisa Cathedral Italy marble facade" },
  { re: /피사의\s*사탑|Leaning Tower of Pisa/i, en: "Leaning Tower of Pisa cathedral square" },
  { re: /아씨시|아시시|Assisi/i, en: "Basilica of Saint Francis Assisi hilltop" },
  { re: /폼페이|Pompeii/i, en: "Pompeii ancient ruins Mount Vesuvius" },
  { re: /소렌토\s*전망대|Sorrento\s*viewpoint/i, en: "Sorrento cliff coast Amalfi viewpoint" },
  { re: /^소렌토$|Sorrento/i, en: "Sorrento Amalfi Coast cliff town" },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: 이탈리아·영국 일주 명소 — manifest
  { re: /친퀘\s*테레|친퀘테레|Cinque\s*Terre/i, en: "Cinque Terre colorful cliff villages" },
  { re: /꼬모\s*호|호수\s*꼬모|Lake\s*Como|^꼬모$|Como\s*Lake/i, en: "Lake Como Bellagio waterfront" },
  { re: /나폴리|Naples|Napoli/i, en: "Naples bay Vesuvius skyline" },
  { re: /플로렌스|피렌체|Florence|Firenze/i, en: "Florence Duomo historic center" },
  { re: /^로마$|^Rome$|^Roma$/i, en: "Colosseum Rome amphitheater" },
  { re: /옥스포드|Oxford/i, en: "Oxford University colleges spires" },
  { re: /스트래트포드|Stratford[\s-]*upon[\s-]*Avon|셰익스피어/i, en: "Stratford upon Avon Shakespeare" },
  { re: /리버풀|Liverpool/i, en: "Liverpool Albert Dock waterfront" },
  { re: /체스터|Chester/i, en: "Chester Roman walls old town" },
  { re: /윈더미어|Windermere/i, en: "Lake Windermere Lake District" },
  { re: /글라스미어|Grasmere/i, en: "Grasmere Lake District village" },
  { re: /에딘버러\s*성|Edinburgh\s*Castle/i, en: "Edinburgh Castle Scotland" },
  { re: /에딘버러|Edinburgh/i, en: "Edinburgh Castle Royal Mile" },
  { re: /벨파스트|Belfast/i, en: "Belfast City Hall Northern Ireland" },
  { re: /더블린|Dublin/i, en: "Dublin Temple Bar old town" },
  { re: /콘위|Conwy|Conway\s*Castle/i, en: "Conwy Castle Wales" },
  { re: /글로스터|Gloucester/i, en: "Gloucester Cathedral England" },
  { re: /바이버리|Bibury/i, en: "Bibury Arlington Row Cotswolds" },
  { re: /코츠월드|Cotswolds?/i, en: "Cotswolds stone village England" },
  { re: /^바스$|\bBath\b|로마\s*목욕탕|Roman\s*Baths/i, en: "Bath Roman Baths England" },
  { re: /솔즈베리|Salisbury|스톤헨지|Stonehenge/i, en: "Stonehenge Salisbury Plain" },
  { re: /^런던$|^London$/i, en: "Tower Bridge London Thames" },
  { re: /바티칸\s*박물관|Vatican\s*Museums/i, en: "Vatican Museums spiral staircase Rome" },
  { re: /성\s*베드로|St\.?\s*Peter'?s?\s*Basilica|바티칸/i, en: "St Peter's Basilica Vatican square" },
  { re: /루앙\s*대성당|Rouen\s*Cathedral/i, en: "Rouen Cathedral Normandy facade" },
  { re: /^루앙$|Rouen/i, en: "Rouen Cathedral Normandy old town" },
  { re: /드오빌|Deauville/i, en: "Deauville beach Normandy boardwalk" },
  { re: /지베르니|Giverny/i, en: "Giverny Monet garden Normandy" },
  { re: /옹플뢰르|Honfleur/i, en: "Honfleur harbor Normandy colorful houses" },
  { re: /케언|Caen/i, en: "Caen Memorial Normandy museum" },
  { re: /베로나|Verona/i, en: "Verona Arena / Roman amphitheater" },
  { re: /시에나|Siena/i, en: "Siena Piazza del Campo / Tuscany / wide angle" },
  { re: /피엔자|Pienza/i, en: "Pienza Tuscany / hill town / wide angle" },
  { re: /시뇨리아|Signoria/i, en: "Piazza della Signoria Florence / Palazzo Vecchio / daytime" },
  { re: /베키오|Ponte Vecchio/i, en: "Ponte Vecchio Florence / Arno River / wide angle" },
  { re: /우피치|Uffizi/i, en: "Uffizi Gallery Florence / courtyard / front view" },
  // 피렌체·Florence는 상단「플로렌스|피렌체」SSOT — 중복 도시 catch-all 제거
  { re: /산\s*지미냐노|San Gimignano/i, en: "San Gimignano medieval towers / Tuscany hills / wide angle" },
  { re: /베로나|Verona/i, en: "Verona Arena / Roman amphitheater / front view" },
  { re: /오르티세이|Ortisei/i, en: "Ortisei Dolomites / alpine village / wide angle" },
  { re: /볼차노|Bolzano/i, en: "Bolzano South Tyrol / Dolomites gateway / street view" },
  { re: /코르티나|Cortina/i, en: "Cortina d Ampezzo Dolomites / mountain peaks / wide angle" },
  { re: /베니스|Venice|Venezia/i, en: "Venice Grand Canal / gondolas / wide angle" },
  { re: /산\s*마리노|San Marino/i, en: "San Marino historic fortress / hilltop view / wide angle" },
  { re: /몬테카티니|Montecatini/i, en: "Montecatini Terme spa town / Tuscany / street view" },
  { re: /볼로냐|Bologna/i, en: "Bologna Two Towers / historic center / front view" },
  { re: /마르쿠스|St\.?\s*Mark|산\s*마르코/i, en: "St Mark's Basilica Venice / Piazza San Marco / front view" },
  { re: /요호|Yoho/i, en: "Yoho National Park / Emerald Lake / wide angle" },
  { re: /페이토|Peyto/i, en: "Peyto Lake / turquoise water / overlook view" },
  { re: /아사바스카|Athabasca/i, en: "Athabasca Falls / Rocky Mountains / wide angle" },
  { re: /레이크\s*루이스|Lake Louise/i, en: "Lake Louise / turquoise lake / mountain backdrop" },
  { re: /모레인|Moraine/i, en: "Moraine Lake / Valley of Ten Peaks / wide angle" },
  { re: /보우\s*폭포|Bow Falls/i, en: "Bow Falls Banff / river cascade / wide angle" },
  { re: /미네완카|Minnewanka/i, en: "Lake Minnewanka Banff / mountain lake / wide angle" },
  { re: /캘거리|Calgary/i, en: "Calgary Tower / downtown skyline / wide angle" },
  { re: /밴프|Banff/i, en: "Banff townsite / Rocky Mountains / street view" },
  { re: /고랑서|鼓浪屿|Gulangyu/i, en: "Gulangyu Island" },
  { re: /남정토루|Nanjing Tulou/i, en: "Nanjing Tulou Fujian" },
  { re: /유창루|Hongkeng/i, en: "Hongkeng Tulou Cluster" },
  { re: /탑하촌|Taxia/i, en: "Taxia Tulou Village" },
  { re: /숙장화원|Shuzhuang/i, en: "Shuzhuang Garden Gulangyu" },
  { re: /일광암|Sunlight Rock/i, en: "Sunlight Rock Gulangyu" },
  { re: /환도로|Huandao/i, en: "Xiamen Huandao Road" },
  { re: /증조안|Zengcuoan/i, en: "Zengcuoan Xiamen" },
  { re: /남보타사|Nanputuo/i, en: "Nanputuo Temple" },
  { re: /(?:하문|샤먼|厦門|厦门|Xiamen).{0,20}중산로|중산로.{0,20}(?:하문|샤먼|厦門|厦门|Xiamen)/u, en: "Zhongshan Road Xiamen" },
  { re: /(?:칭다오|청도|Qingdao).{0,20}중산로|중산로.{0,20}(?:칭다오|청도|Qingdao)/u, en: "Zhongshan Road Qingdao" },
  { re: /코타\s*키나발루|Kota\s*Kinabalu/i, en: 'Kota Kinabalu Malaysia' },
  { re: /페트로나스|Petronas/i, en: 'Petronas Twin Towers Kuala Lumpur' },
  { re: /바투\s*동굴|Batu\s*Caves/i, en: 'Batu Caves Kuala Lumpur' },
  { re: /메르데카\s*광장|Merdeka\s*Square/i, en: 'Merdeka Square Kuala Lumpur' },
  { re: /쳉훈텡|Cheng\s*Hoon\s*Teng/i, en: 'Cheng Hoon Teng Temple Malacca' },
  { re: /쿠알라룸푸르\s*왕궁|Istana\s*Negara/i, en: 'Istana Negara Kuala Lumpur' },
  { re: /겐팅\s*하이랜드|겐팅|Genting/i, en: 'Genting Highlands Malaysia' },
  { re: /(?:^|\s)레(?:\s|$|-)(?=.*(?:왕궁|시장|Palace|Ladakh|라다크))/u, en: "Leh Palace Ladakh" },
  { re: /^(?:레|Leh)$/iu, en: "Leh Palace Ladakh" },
  { re: /\bLeh(?:\s+Palace|\s+Ladakh)?\b/i, en: "Leh Palace Ladakh" },
  { re: /씨엠립|시엠립|Siem\s*Reap/i, en: 'Angkor Wat Cambodia temple sunrise' },
  { re: /앙코르\s*와트|Angkor\s*Wat/i, en: 'Angkor Wat Cambodia temple sunrise' },
  { re: /바이욘|Bayon/i, en: 'Bayon temple Angkor Cambodia stone faces' },
  { re: /타프롬|Ta\s*Prohm/i, en: 'Ta Prohm temple Angkor Cambodia jungle roots' },
  { re: /바푸온|Baphuon/i, en: 'Baphuon temple Angkor Cambodia pyramid' },
  { re: /코끼리\s*테라스|Elephant\s*Terrace/i, en: 'Elephant Terrace Angkor Cambodia' },
  { re: /톤레\s*삽|Tonle\s*Sap/i, en: 'Tonle Sap lake floating village Cambodia' },
  { re: /하롱\s*베이|Halong\s*Bay|Ha\s*Long\s*Bay/i, en: 'Halong Bay Vietnam' },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: 하노이·하롱 — Montenegro Titov 오매칭 금지 — manifest
  { re: /티톱\s*섬|Ti\s*Top|Titop/i, en: 'Ti Top Island Halong Bay' },
  { re: /석회\s*동굴|Surprise\s*Cave|Hang\s*Sung\s*Sot/i, en: 'Surprise Cave Halong Bay' },
  { re: /쩐꾸옥|Tran\s*Quoc|Tran\s*Quốc/i, en: 'Tran Quoc Pagoda Hanoi' },
  { re: /옌뜨|Yen\s*Tu|Yên\s*Tử/i, en: 'Yen Tu National Park' },
  { re: /바딘\s*광장|Ba\s*Dinh/i, en: 'Ba Dinh Square Hanoi' },
  { re: /한기둥\s*사원|One\s*Pillar\s*Pagoda/i, en: 'One Pillar Pagoda Hanoi' },
  { re: /호치민\s*생가|Ho\s*Chi\s*Minh\s*(?:Stilt\s*)?House|호찌민\s*생가/i, en: 'Ho Chi Minh Stilt House Hanoi' },
  { re: /호안끼엠|Hoan\s*Kiem/i, en: 'Hoan Kiem Lake Hanoi' },
  { re: /하노이.{0,40}서호|서호(?=.{0,24}하노이)|West\s*Lake\s*Hanoi/iu, en: 'West Lake Hanoi' },
  { re: /서호/u, en: 'West Lake Hanoi' },
  { re: /삼형제|Three\s*Brothers/i, en: 'Three Brothers Houses Riga Latvia' },
  { re: /이누야마|Inuyama/i, en: 'Inuyama Castle Japan' },
  { re: /아쓰타|Atsuta/i, en: 'Atsuta Shrine Nagoya Japan' },
  { re: /시라카와|Shirakawa/i, en: 'Shirakawa-go gassho farmhouses Japan' },
  { re: /가미코치|Kamikochi/i, en: 'Kamikochi Japan Alps valley' },
  { re: /다카야마|Takayama/i, en: 'Takayama old town Japan' },
  { re: /마요르\s*광장|Plaza\s*Mayor/i, en: 'Plaza Mayor Madrid Spain' },
  { re: /그란\s*비아|Gran\s*Via/i, en: 'Gran Via Madrid Spain boulevard' },
  { re: /톨레도|Toledo/i, en: 'Toledo Spain old town cathedral' },
  { re: /세고비아|Segovia/i, en: 'Segovia Aqueduct Roman Spain' },
  { re: /카파도키아|Cappadocia/i, en: 'Cappadocia Fairy Chimneys' },
  { re: /파묵칼레|Pamukkale/i, en: 'Pamukkale Travertine Terraces' },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: India AWP902 — Lodhi/Bahai/Akshardham·짧은 landmark — manifest
  { re: /타지\s*마할|Taj\s*Mahal/i, en: 'Taj Mahal' },
  { re: /아그라\s*성|Agra\s*Fort/i, en: 'Agra Fort' },
  { re: /하와\s*마할|Hawa\s*Mahal/i, en: 'Hawa Mahal' },
  { re: /암베르\s*성|Amber\s*Fort/i, en: 'Amber Fort' },
  { re: /나하르가르\s*성|Nahargarh\s*Fort/i, en: 'Nahargarh Fort' },
  { re: /잔타르\s*만타르|Jantar\s*Mantar/i, en: 'Jantar Mantar' },
  { re: /꾸뜹\s*미나르|쿠트브|Qutub\s*Minar|Qutb\s*Minar/i, en: 'Qutub Minar' },
  { re: /인도\s*게이트|인디아\s*게이트|인디아게이트|India\s*Gate/i, en: 'India Gate' },
  { re: /로디\s*가든|Lodhi\s*Garden|Lodi\s*Garden/i, en: 'Lodhi Garden' },
  { re: /바하이\s*사원|Lotus\s*Temple|Bah[aá]['ʼ]?[ií]\s*Temple/i, en: 'Lotus Temple' },
  { re: /악차르담|Akshardham/i, en: 'Akshardham Temple' },
  { re: /카주라호|Khajuraho|서부\s*사원군|동부\s*사원군/i, en: 'Khajuraho Temples' },
  { re: /갠지스\s*강|갠지스강|Ganges|Ganga\s*River/i, en: 'Ganges River' },
  { re: /사르나트|Sarnath/i, en: 'Sarnath' },
  { re: /아르띠\s*뿌자|아르티\s*푸자|Ganga\s*Aarti/i, en: 'Ganga Aarti' },
  { re: /후마윤\s*무덤|Humayun/i, en: 'Humayun Tomb' },
  { re: /구르드와라\s*방글라\s*사힙|Gurudwara\s*Bangla\s*Sahib/i, en: 'Gurudwara Bangla Sahib' },
  { re: /시칸드라\s*성|Sikandra/i, en: 'Sikandra' },
  { re: /아바네리\s*찬드|Abaneri|Chand\s*Baori/i, en: 'Chand Baori' },
  { re: /라헤마|Lahemaa/i, en: 'Lahemaa National Park Estonia coastal forest' },
  { re: /알렉산더\s*네브스키|Alexander\s*Nevsky/i, en: 'Alexander Nevsky Cathedral Tallinn Estonia' },
  { re: /예류|Yehliu/i, en: 'Yehliu Geopark Taiwan rock formations' },
  { re: /단수이|Danshui|Tamsui|홍마오청|Fort\s*San\s*Domingo/i, en: 'Danshui Old Street Taiwan waterfront' },
  { re: /벳푸|Beppu/i, en: 'Beppu hot springs steam Japan' },
  { re: /아소|Mount\s*Aso|阿蘇/i, en: 'Mount Aso volcano caldera Japan' },
  { re: /밴프|Banff/i, en: 'Lake Louise Banff National Park Canada' },
  { re: /모레인|Moraine/i, en: 'Moraine Lake Banff Canada turquoise' },
  { re: /로이\s*하자|Lake\s*Louise/i, en: 'Lake Louise Banff Canada turquoise' },
  { re: /밴쿠버|Vancouver/i, en: 'Vancouver Canada harbor mountains' },
  { re: /그랜빌|Granville/i, en: 'Granville Island Vancouver Canada' },
  { re: /(?:르메르디앙|Le\s*Meridien|Meridien)/i, en: "Maldives overwater bungalow resort aerial" },
  { re: /하우스\s*리프|House\s*Reef/i, en: "Maldives house reef snorkeling turquoise water" },
  { re: /Bodu\s*Finolhu|보두\s*피놀후/i, en: "Maldives white sand beach palm trees aerial" },
  { re: /달랏|Da Lat|Dalat/i, en: "Da Lat Vietnam highland pine forest city" },
  { re: /나트랑|Nha Trang/i, en: "Nha Trang beach Vietnam turquoise sea" },
  { re: /비엔티안|비엔티엔|Vientiane/i, en: "Pha That Luang Vientiane golden stupa" },
  { re: /방비엥|Vang Vieng/i, en: "Vang Vieng Nam Song river karst mountains" },
  { re: /블루\s*라군|Blue Lagoon/i, en: "Blue Lagoon Vang Vieng emerald water" },
  { re: /파투싸이|Patuxai/i, en: "Patuxai Victory Monument Vientiane" },
  { re: /타틀루앙|Pha That Luang/i, en: "Pha That Luang Vientiane golden stupa front view" },
  { re: /후룬베이얼\s*대초원|Hulunbuir Grassland/i, en: "Hulunbuir Grassland / rolling green hills / wide angle" },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: 후룬베이얼 역사 박물관 ≠ Istanbul — manifest
  { re: /후룬베이얼\s*역사\s*박물관|Hulunbuir\s*History\s*Museum/i, en: "Hulunbuir History Museum" },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: 징기스칸 광장 ≠ Ordos 기마상 — manifest
  { re: /(?:칭기즈|징기스)\s*칸\s*광장|Genghis\s*Khan\s*Square/i, en: "Genghis Khan Square Hailar" },
  { re: /모리거러|Morigele/i, en: "Morigele River / grassland valley / wide angle" },
  { re: /만주리|Manzhouli/i, en: "Manzhouli border city / Russian architecture / street view" },
  { re: /마트료시카|Matryoshka/i, en: "Matryoshka Square Manzhouli / colorful dolls plaza / front view" },
  { re: /후룬베이얼\s*고성|Hulunbuir Old/i, en: "Hulunbuir Old Town / Qing dynasty gate / front view" },
  { re: /하이라얼|Hailar/i, en: "Hailar city / Inner Mongolia steppe gateway / street view" },
  { re: /포나가르|Po Nagar|Cham Towers/i, en: "Po Nagar Cham Towers Nha Trang / ancient towers / front view" },
  { re: /선셋\s*타운|Sunset\s*Town/i, en: "Sunset Town Phu Quoc" },
  { re: /키스\s*브릿지|Kiss\s*Bridge/i, en: "Kiss Bridge Phu Quoc" },
  { re: /선셋\s*사나토|Sunset\s*Sanato|손트랑/i, en: "Sunset Sanato Phu Quoc beach" },
  { re: /그랜드\s*월드|Grand\s*World/i, en: "Grand World Phu Quoc" },
  { re: /사오\s*비치|Sao\s*Beach/i, en: "Phu Quoc Sao Beach Vietnam" },
  // REGRESSION-FREEZE[register-schedule-trip-image-keyword-dedupe]: Hon Thom·Duong Dong before bare Phu Quoc — manifest
  { re: /혼똠|혼똔|Hon\s*Thom|썬월드\s*혼|썬월드|세계\s*최장\s*케이블카/i, en: "Phu Quoc Hon Thom Cable Car" },
  { re: /딘커우|Dinh\s*Cau/i, en: "Dinh Cau Temple Phu Quoc" },
  { re: /쯔엉동\s*야시장|쯔엉동|Duong\s*Dong/i, en: "Duong Dong Night Market Phu Quoc" },
  { re: /부이페스트|Vui\s*Pnest/i, en: "Vui Pnest Night Market Phu Quoc" },
  { re: /소나시\s*야시장|Sonasea/i, en: "Sonasea Night Market Phu Quoc" },
  { re: /호국사|Ho\s*Quoc/i, en: "Ho Quoc Pagoda Phu Quoc" },
  { re: /후추\s*농장|Pepper\s*Farm/i, en: "Phu Quoc Pepper Farm" },
  { re: /푸꾸옥|Phu\s*Quoc|푸꾹옥/i, en: "Phu Quoc" },
  { re: /두브로브니크|Dubrovnik/i, en: "Dubrovnik Old Town walls Croatia" },
  { re: /플리트비체|Plitvice/i, en: "Plitvice Lakes National Park Croatia" },
  { re: /스플리트|Split/i, en: "Diocletian Palace Split Croatia" },
  { re: /자그레브|Zagreb/i, en: "Zagreb Cathedral Croatia" },
  { re: /나트랑|Nha Trang/i, en: "Nha Trang beach Vietnam / turquoise sea / wide angle" },
  { re: /달랏|Da Lat|Dalat/i, en: "Da Lat Vietnam highland / pine hills / wide angle" },
  { re: /나이아가라|Niagara/i, en: "Niagara Falls waterfall mist wide angle" },
  { re: /링컨\s*기념관|Lincoln\s*Memorial/i, en: "Lincoln Memorial Washington DC front view" },
  { re: /제퍼슨\s*기념관|Jefferson\s*Memorial/i, en: "Jefferson Memorial Washington DC dome reflection" },
  { re: /백악관|White\s*House/i, en: "White House Washington DC north facade" },
  { re: /쉔부른\s*궁전|쇤브룬\s*궁전|Schonbrunn/i, en: "Schonbrunn Palace Vienna" },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: 프라하·동유럽 명소 — manifest
  { re: /프라하\s*성|Prague\s*Castle/i, en: "Prague Castle" },
  { re: /카를\s*교|카를교|Charles\s*Bridge/i, en: "Charles Bridge Prague" },
  { re: /천문\s*시계|Astronomical\s*Clock|올드\s*타운\s*스퀘어|구시가(?:지)?\s*광장/i, en: "Prague Old Town Square" },
  { re: /카를로비\s*바리|Karlovy\s*Vary|카를스바트/i, en: "Karlovy Vary colonnade" },
  { re: /플젠|플젠시|Plze[nň]|Pilsen/i, en: "Plzen Republic Square" },
  { re: /브르노|Brno/i, en: "Spilberk Castle Brno" },
  { re: /브라티슬라바\s*성|Bratislava\s*Castle/i, en: "Bratislava Castle" },
  { re: /브라티슬라바|Bratislava/i, en: "Bratislava Castle Danube" },
  { re: /짤즈?\s*캄머\s*굿|Salzkammergut/i, en: "Salzkammergut lake Austria" },
  { re: /린츠|Linz/i, en: "Linz Hauptplatz Austria" },
  { re: /체스케\s*부데요비체|Česk[eé]\s*Bud[eě]jovice|Ceske\s*Budejovice/i, en: "Ceske Budejovice square" },
  { re: /체스키\s*크(?:룸|롬)로프|Český\s*Krumlov|Cesky\s*Krumlov/i, en: "Cesky Krumlov Castle Czech Republic" },
  { re: /이발사\s*다리|Barber\s*Bridge/i, en: "Cesky Krumlov old town bridge" },
  { re: /미라벨|Mirabell/i, en: "Mirabell Gardens Salzburg" },
  { re: /모짜르트|Mozart/i, en: "Mozart birthplace Salzburg" },
  { re: /잘츠부르크|Salzburg|잘쯔부르크/i, en: "Hohensalzburg Fortress Salzburg" },
  { re: /자다르|Zadar/i, en: "Church of St Donatus Zadar Croatia" },
  { re: /세인트\s*도나트|Saint\s*Donatus/i, en: "Church of St Donatus Zadar Croatia" },
  { re: /렉터\s*궁전|Rector\s*Palace/i, en: "Rector Palace Dubrovnik" },
  { re: /할슈타트|Hallstatt/i, en: "Hallstatt lake village Austria" },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: 독일 일주 명소 — manifest
  { re: /노이슈반슈타인|Neuschwanstein/i, en: "Neuschwanstein Castle Bavaria" },
  { re: /헤렌킴제|Herrenchiemsee/i, en: "Herrenchiemsee Palace Bavaria" },
  { re: /체칠리엔호프|Cecilienhof/i, en: "Cecilienhof Palace Potsdam" },
  { re: /상수시|Sanssouci/i, en: "Sanssouci Palace Potsdam" },
  { re: /브란덴부르크\s*문|Brandenburg\s*Gate/i, en: "Brandenburg Gate Berlin" },
  { re: /(?:베를린\s*)?구박물관|Altes\s*Museum/i, en: "Altes Museum Berlin" },
  { re: /드레스덴\s*성모|Frauenkirche\s*Dresden|Zwinger/i, en: "Dresden Frauenkirche Cathedral" },
  { re: /뉘른베르크\s*(?:성|고성)|Nuremberg\s*Castle/i, en: "Nuremberg Castle" },
  // 뮌헨 성모교회 — 도시 없는 Frauenkirche Cathedral은 타일 bleed 위험
  { re: /성모교회|Frauenkirche\s*Munich|Marienkirche/i, en: "Marienplatz Square Munich" },
  { re: /뤼데스하임|R[uü]desheim|Rudesheim/i, en: "Rudesheim Rhine cable car" },
  { re: /로텐부르크|Rothenburg/i, en: "Rothenburg ob der Tauber" },
  { re: /퓌센|F[uü]ssen|Fussen/i, en: "Neuschwanstein Castle Bavaria" },
  { re: /킴제|Chiemsee/i, en: "Herrenchiemsee Palace Bavaria" },
  { re: /밤베르크|Bamberg/i, en: "Bamberg Old Town" },
  { re: /포츠담|Potsdam/i, en: "Sanssouci Palace Potsdam" },
  { re: /뉘른베르크|Nuremberg|N[uü]rnberg/i, en: "Nuremberg Castle" },
  { re: /드레스덴|Dresden/i, en: "Dresden Frauenkirche Cathedral" },
  { re: /뮌헨|Munich|M[uü]nchen/i, en: "Marienplatz Square Munich" },
  { re: /베를린|Berlin/i, en: "Brandenburg Gate Berlin" },
  { re: /프랑크푸르트|Frankfurt/i, en: "Romerberg Square Frankfurt" },
  { re: /인스부르크|Innsbruck/i, en: "Innsbruck Golden Roof Austria" },
  { re: /스와로브스키\s*크리스탈|Swarovski/i, en: "Swarovski Kristallwelten Wattens" },
  { re: /헝가리\s*국회|부다페스트.{0,16}국회/i, en: "Hungarian Parliament Budapest" },
  { re: /어부의\s*요새/u, en: "Fisherman's Bastion Budapest" },
  { re: /부다\s*왕궁/u, en: "Buda Castle Budapest" },
  { re: /영웅\s*광장/u, en: "Heroes Square Budapest" },
  { re: /제로니모스|제로니무스|Jer[oó]nimos/i, en: "Jeronimos Monastery Lisbon" },
  { re: /벨렘\s*탑|Bel[eé]m\s*Tower/i, en: "Belem Tower Lisbon" },
  { re: /코메르시우|Commerce\s*Square/i, en: "Commerce Square Lisbon" },
  { re: /헤갈레이라|Pena\s*Palace/i, en: "Pena Palace Sintra" },
  { re: /까보다로까|Cabo\s*da\s*Roca|로카\s*곶/i, en: "Cabo da Roca Portugal" },
  { re: /신트라|Sintra/i, en: "Pena Palace Sintra" },
  { re: /카스카이스|Cascais/i, en: "Cascais beach Portugal" },
  { re: /파티마|Fatima/i, en: "Sanctuary of Fatima Portugal" },
  { re: /봉\s*헤수스|Bom\s*Jesus/i, en: "Bom Jesus do Monte Braga" },
  { re: /브라가\s*대성당|Braga\s*Cathedral/i, en: "Braga Cathedral" },
  { re: /클레리구스|Cl[eé]rigos/i, en: "Clerigos Tower Porto" },
  { re: /포르투\s*대성당|Porto\s*Cathedral/i, en: "Porto Cathedral" },
  { re: /상\s*벤투|Sao\s*Bento/i, en: "Sao Bento Station Porto" },
  { re: /몰리세이루|Moliceiro/i, en: "Moliceiro boats Aveiro" },
  { re: /오비두스|Obidos/i, en: "Obidos medieval town Portugal" },
  { re: /상비센테|Cape\s*St\.?\s*Vincent/i, en: "Cape St Vincent Portugal" },
  { re: /사그레스성|Sagres\s*Fortress/i, en: "Sagres Fortress Portugal" },
  { re: /사그레스|Sagres/i, en: "Sagres Portugal" },
  { re: /리스본|Lisbon/i, en: "Jeronimos Monastery Lisbon" },
  { re: /포르투(?!갈)|Porto(?!\s*marin)/i, en: "Clerigos Tower Porto" },
  { re: /시청사와\s*국회의사당/u, en: "Vienna Rathaus Austrian Parliament" },
  {
    re: /(?:워싱턴|Washington\s*D\.?\s*C\.?|미국\s*동부|미\s*동부).{0,24}국회의사당|국회의사당.{0,24}(?:워싱턴|Washington)|Capitol\s*Building|US\s*Capitol/i,
    en: "United States Capitol dome Washington DC",
  },
  {
    re: /(?:워싱턴|Washington\s*D\.?\s*C\.?|미국\s*동부|스미소니언|Smithsonian).{0,48}자연사\s*박물관|자연사\s*박물관.{0,48}(?:워싱턴|Washington|스미소니언|Smithsonian)/i,
    en: "Smithsonian National Museum of Natural History Washington DC",
  },
  { re: /아부다비\s*자연사|자이드\s*내셔널|Zayed\s*National\s*Museum/i, en: "Sheikh Zayed Grand Mosque Abu Dhabi" },
  { re: /루브르\s*아부다비|Louvre\s*Abu\s*Dhabi|사디얗\s*아일랜드|사디얏\s*아일랜드/i, en: "Louvre Abu Dhabi Saadiyat Island" },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: UAE EMP340 Day2 — Emirates Palace·왕궁·모스크·분수·에티하드 — manifest
  { re: /에미레이트\s*팰리스|Emirates\s*Palace/i, en: "Emirates Palace Abu Dhabi" },
  { re: /아부다비\s*왕궁|Qasr\s*Al\s*Watan|Presidential\s*Palace\s*Abu/i, en: "Qasr Al Watan Abu Dhabi" },
  { re: /그랜드\s*모스크|Sheikh\s*Zayed\s*Grand\s*Mosque|자이드\s*그랜드\s*모스크/i, en: "Sheikh Zayed Grand Mosque Abu Dhabi" },
  { re: /에티하드\s*타워|Etihad\s*Tower/i, en: "Etihad Towers Abu Dhabi" },
  { re: /두바이몰\s*분수|분수쇼\s*워크|Dubai\s*Fountain|두바이\s*분수/i, en: "Dubai Fountain Dubai Mall" },
  { re: /도우\s*크루즈|Dhow\s*Cruise|크루즈\s*야경/i, en: "Dubai Creek Dhow Cruise" },
  { re: /버즈\s*칼리파|Burj\s*Khalifa/i, en: "Burj Khalifa Dubai skyline" },
  { re: /두바이\s*프레임|Dubai\s*Frame/i, en: "Dubai Frame Zabeel Park" },
  { re: /바스타키아|Al\s*Fahidi|알\s*파히디|Al\s*Seef|알\s*시프/i, en: "Al Fahidi Historical District Dubai" },
  { re: /팜\s*주메이라|Palm\s*Jumeirah/i, en: "Palm Jumeirah Dubai aerial" },
  { re: /사막\s*사파리|Desert\s*Safari/i, en: "Dubai desert safari dunes sunset" },
  { re: /쉬르반샤|Shirvanshah/i, en: "Shirvanshah Palace Baku Azerbaijan" },
  { re: /메이든\s*타워|Maiden\s*Tower/i, en: "Maiden Tower Baku old city" },
  // REGRESSION-FREEZE[lottetour-singapore-register-quality]: 바쿠테(Bakute)≠Baku — manifest
  { re: /바쿠(?!테)|(?<![A-Za-z])Baku(?![A-Za-z])/i, en: "Flame Towers Baku Azerbaijan" },
  { re: /트빌리시|Tbilisi|트빌리/i, en: "Narikala Fortress Tbilisi Georgia" },
  { re: /예레ван|Yerevan|에치미아진/i, en: "Republic Square Yerevan Armenia" },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: 대련·여순 CAP611 — 성해/러시아거리·연화산 일차 오매핑 금지 — manifest
  { re: /성해광장|星海广场|Xinghai\s*Square/i, en: "Xinghai Square Dalian" },
  { re: /동방수성|东方水城|Oriental\s*Water\s*City/i, en: "Oriental Water City Dalian" },
  { re: /(?:서안로|西安路)\s*먹자거리/u, en: "Xian Road Food Street Dalian" },
  { re: /러시아거리|Russian\s*Street/i, en: "Russian Street Dalian" },
  { re: /(?:동관거리|东关街)/u, en: "Dongguan Street Dalian" },
  { re: /여순감옥|旅顺监狱|Lushun\s*Prison/i, en: "Lushun Prison Museum Dalian" },
  { re: /(?:여순)?관동법원|关东法院|旅顺关东/u, en: "Lushun Court Museum Dalian" },
  { re: /연화산|莲花山|Yanhuashan/i, en: "Yanhuashan Viewpoint Dalian" },
  // bare 대련은 CITY soft — 일차 선두「대련 - …」이 Xinghai를 훔치지 않게 (성해광장 규칙 우선)
  { re: /다롄|大连|(?<![A-Za-z])Dalian(?![A-Za-z])/i, en: "Xinghai Square Dalian" },
  { re: /여순(?!감옥|관동|기차)|旅顺(?!监狱)|Lushun(?!\s*(?:Prison|Court))/i, en: "Lushun Port Dalian" },
  { re: /시즈오카|Shizuoka/i, en: "Mount Fuji Shizuoka view" },
  { re: /요나고|Yonago/i, en: "Mount Daisen Yonago Japan" },
  { re: /이즈모|Izumo/i, en: "Izumo Taisha shrine Japan" },
  { re: /마쯔에|Matsue/i, en: "Matsue Castle Japan" },
  { re: /다마즈쿠리|Tamatsukuri/i, en: "Tamatsukuri onsen Japan" },
  { re: /다자이후|Dazaifu/i, en: "Dazaifu Tenmangu shrine Fukuoka" },
  { re: /다케오|Takeo/i, en: "Takeo Onsen Japan" },
  { re: /이올라니|Iolani/i, en: "Iolani Palace Honolulu Hawaii" },
  { re: /카카오코|Kakaako|Kaka.?ako/i, en: "Kakaako street art Honolulu Hawaii" },
  { re: /노스\s*쇼어|North\s*Shore/i, en: "North Shore Oahu Surf Beach" },
  { re: /와이키키|Waikiki/i, en: "Honolulu Waikiki Beach" },
  // bare 오아후 → North Shore 금지 (TIP 자유일·귀국일 블리드). Oahu soft city만.
  { re: /\bOahu\b|오아후/i, en: "Oahu" },
  { re: /다이아몬드\s*헤드|Diamond\s*Head/i, en: "Diamond Head Honolulu crater view" },
  { re: /Pearl\s*Harbor|진주만/i, en: "Pearl Harbor USS Arizona Memorial Hawaii" },
  { re: /하나우마|Hanauma/i, en: "Hanauma Bay Oahu snorkeling" },
  { re: /파인애플\s*농장|Pineapple\s*(?:Farm|Plantation)/i, en: "Pineapple Farm Hawaii" },
  { re: /로드\s*투\s*하나|Road\s*to\s*Hana/i, en: "Road to Hana Maui Hawaii" },
  { re: /와이레아|Wailea/i, en: "Maui Wailea Beach Hawaii" },
  { re: /폴리네시안|Polynesian\s*Cultural/i, en: "Polynesian Cultural Center Oahu Hawaii" },
  { re: /워싱턴\s*국립\s*미술관|National\s*Gallery/i, en: "National Gallery of Art Washington DC" },
  { re: /스카이론|Skylon/i, en: "Skylon Tower Niagara Falls observation deck" },
  { re: /바람의\s*동굴|Cave\s*of\s*the\s*Winds/i, en: "Cave of the Winds Niagara Falls platform" },
  { re: /엠파이어\s*스테이트|Empire\s*State/i, en: "Empire State Building New York skyline" },
  { re: /플랫아이언|Flatiron/i, en: "Flatiron Building New York street view" },
  { re: /그라운드\s*제로|Ground\s*Zero|9\s*\/\s*11/i, en: "One World Trade Center New York memorial" },
  { re: /월\s*스트리트|Wall\s*Street/i, en: "Wall Street New York Charging Bull" },
  { re: /그리니치\s*빌리지|Greenwich\s*Village/i, en: "Greenwich Village New York brownstone street" },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: EAP321 Central Asia — Tashkent/Almaty/Issyk spots · short EN — manifest
  { re: /미노르\s*모스크|Minor\s*Mosque/i, en: 'Minor Mosque' },
  { re: /초르수\s*바자르|Chorsu\s*Bazaar/i, en: 'Chorsu Bazaar' },
  { re: /하르자트\s*이맘|Hazrati\s*Imam|Khast\s*Imam/i, en: 'Hazrati Imam Complex' },
  { re: /황만금\s*박물관|State\s*Museum\s*of\s*History/i, en: 'State Museum of History' },
  { re: /아미르\s*티무르\s*광장|Amir\s*Timur\s*Square/i, en: 'Amir Timur Square' },
  { re: /레기스탄|Registan/i, en: 'Registan Square' },
  { re: /아프로시압|Afrosiyab/i, en: 'Afrosiyab' },
  { re: /울루그벡|Ulugbek|Ulugh\s*Beg/i, en: 'Ulugh Beg Observatory' },
  { re: /구르\s*아미르|Gur[-\s]*e?\s*Amir/i, en: 'Gur-e Amir' },
  { re: /샤히진다|Shah[-\s]*i[-\s]*Zinda/i, en: 'Shah-i-Zinda' },
  { re: /비비하눔|Bibi[-\s]*Khanym/i, en: 'Bibi-Khanym Mosque' },
  { re: /시요브\s*바자르|Siyob\s*Bazaar/i, en: 'Siyob Bazaar' },
  { re: /침볼락|Chimbulak|Shymbulak/i, en: 'Shymbulak' },
  { re: /젠코바|Zenkov/i, en: 'Zenkov Cathedral' },
  { re: /판필로바|Panfilov/i, en: 'Panfilov Park' },
  { re: /아르바트\s*거리|Arbat/i, en: 'Arbat Street' },
  { re: /블랙\s*캐년|Black\s*Canyon/i, en: 'Black Canyon' },
  { re: /루나\s*캐년|Luna\s*Canyon/i, en: 'Luna Canyon' },
  { re: /차른\s*캐년|Charyn\s*Canyon/i, en: 'Charyn Canyon' },
  { re: /악수\s*온천|Aksu\s*(?:Hot\s*)?Spring/i, en: 'Aksu Hot Springs' },
  { re: /촐폰\s*아타|Cholpon[-\s]*Ata/i, en: 'Cholpon Ata' },
  { re: /이식쿨|Issyk[-\s]*Kul/i, en: 'Issyk Kul Lake' },
  { re: /알라아르차|Ala[-\s]*Archa/i, en: 'Ala Archa National Park' },
  { re: /알라투\s*광장|Ala[-\s]*Too\s*Square/i, en: 'Ala Too Square' },
  { re: /타임스퀘어|Times\s*Square/i, en: "Times Square Broadway New York night" },
  { re: /(?:뉴욕|New\s*York|NYC).*(?:브로드웨이|Broadway)|(?:브로드웨이|Broadway).*(?:뉴욕|New\s*York|NYC)/i, en: "Times Square Broadway New York night" },
  { re: /5번가|Fifth\s*Avenue/i, en: "Fifth Avenue New York street view" },
  { re: /노트르담\s*대성당|Notre\s*Dame\s*Basilica/i, en: "Notre Dame Basilica Montreal interior blue vault" },
  { re: /몽모랑시\s*폭포|Montmorency/i, en: "Montmorency Falls Quebec suspension bridge" },
  { re: /천섬|Thousand\s*Islands/i, en: "Thousand Islands St Lawrence River aerial" },
  { re: /레이크\s*조지|Lake\s*George/i, en: "Lake George New York Adirondack mountains" },
  { re: /오저블\s*케이즘|Ausable\s*Chasm/i, en: "Ausable Chasm New York gorge waterfall" },
  { re: /마추픽chu|Machu\s*Picchu|마추\s*픽chu/i, en: "Machu Picchu ancient ruins mountain Peru" },
  { re: /올란타이탐보|Ollantaytambo/i, en: "Ollantaytambo Inca ruins Sacred Valley Peru" },
  { re: /사크레드|Sacred\s*Valley/i, en: "Sacred Valley Peru Urubamba river mountains" },
  { re: /마라스|Maras/i, en: "Maras salt ponds Sacred Valley Peru terraces" },
  { re: /사크사이와만|Sacsayhuaman/i, en: "Sacsayhuaman Cusco Inca fortress walls" },
  { re: /코리칸차|Coricancha|Qorikancha/i, en: "Coricancha Temple Cusco golden courtyard" },
  { re: /세계\s*3대\s*폭포\s*이과수|이과수\s*폭포/i, en: "Iguazu Falls waterfall panorama" },
  { re: /플라자\s*데\s*마요|Plaza\s*de\s*Mayo/i, en: "Plaza de Mayo Buenos Aires pink house" },
  { re: /라\s*보카|La\s*Boca|Caminito/i, en: "La Boca Caminito Buenos Aires colorful street" },
  { re: /부에노스\s*아이레스|부에노스아이레스|Buenos\s*Aires/i, en: "Buenos Aires Obelisco avenue night" },
  { re: /채플테펙|Chapultepec/i, en: "Chapultepec Castle Mexico City hilltop" },
  { re: /소치밀로|Xochimilco/i, en: "Xochimilco floating gardens Mexico City trajineras" },
  { re: /축복.*예수|Blessing.*Jesus|예수\s*상\s*전망|Yesus\s*Blessing/i, en: "Blessing Jesus Statue Manado North Sulawesi" },
  { re: /마카테테|Makatete/i, en: "Makatete Hill Manado Sulawesi viewpoint" },
  { re: /오르도스\s*박물관|Ordos\s*Museum/i, en: "Ordos Museum Inner Mongolia" },
  { re: /몰디브\s*리조트|Maldives\s*resort|체크아웃\s*준비/i, en: "Maldives overwater bungalow resort" },
  { re: /코르코바도|Corcovado/i, en: "Corcovado Christ the Redeemer Rio de Janeiro" },
  { re: /웨스트민스터|베스(?:트)?민스터|Westminster(?:\s*Abbey)?/i, en: "Westminster Abbey London Gothic facade" },
  { re: /로벤\s*섬|Robben\s*Island/i, en: "Robben Island Cape Town Table Bay view" },
  { re: /미라보라벤더|Valensole|라벤더\s*밭|Lavender\s*field/i, en: "Valensole lavender plateau Provence" },
  { re: /고대\s*극장|Orange|오랑주|Th[eé]atre/i, en: "Orange ancient Roman theatre Provence" },
  { re: /루(?:베|르)(?:봉|손)|Roussillon|빨간\s*마을/i, en: "Roussillon ochre village Provence" },
  { re: /세네끄|Senanque|S[eé]nanque/i, en: "Senanque Abbey Provence lavender" },
  // bare 라벤더 alone → Provence only with 프로방스 context (Hokkaido 라벤더 소프트는 위 규칙)
  { re: /(?:프로방스|Provence).{0,30}(?:라벤더|Lavender)|(?:라벤더|Lavender).{0,30}(?:프로방스|Provence)|\bProvence\b/i, en: "Provence lavender fields Valensole plateau" },
  { re: /상하이\s*디즈니|Shanghai\s*Disney|디즈니랜드/i, en: "Shanghai Disneyland enchanted storybook castle" },
  { re: /우유니\s*사막|Uyuni|볼리비아\s*우유니/i, en: "Salar de Uyuni salt flats mirror Bolivia" },
  { re: /이과수\s*폭포|Iguazu|Iguassu/i, en: "Iguazu Falls Brazil Argentina waterfall panorama" },
  { re: /쿠스코|Cusco|Cuzco/i, en: "Cusco Peru Plaza de Armas colonial architecture" },
  { re: /아구아스\s*칼리엔테스|Aguas\s*Calientes/i, en: "Aguas Calientes Machu Picchu gateway town" },
  { re: /가루다\s*공원|Garuda\s*Wisnu/i, en: "Garuda Wisnu Kencana" },
  { re: /울루와뚜|Uluwatu/i, en: "Uluwatu Temple" },
  { re: /멜라스티|Melasti/i, en: "Melasti Beach" },
  { re: /빠당빠당|Padang\s*Padang/i, en: "Padang Padang Beach" },
  { re: /비치\s*클럽|Beach\s*Club/i, en: "Bali Beach Club" },
  { re: /뜨갈랄랑|Tegalalang/i, en: "Tegalalang Rice Terrace" },
  { re: /발리\s*해변/i, en: "Bali beach sunset" },
  { re: /프린스(?:턴|톤)\s*대학|Princeton\s*University/i, en: "Princeton University campus" },
  { re: /필라델피아|Philadelphia/i, en: "Independence Hall Philadelphia" },
  { re: /인디펜던스\s*홀|Independence\s*Hall/i, en: "Independence Hall Philadelphia" },
  { re: /하버드\s*대학|Harvard\s*University/i, en: "Harvard University campus" },
  { re: /예일\s*대학|Yale\s*University/i, en: "Yale University campus" },
  { re: /우드버리\s*아울|Woodbury\s*Common/i, en: "Woodbury Common Premium Outlets" },
  { re: /센트럴\s*파크|Central\s*Park/i, en: "Central Park New York" },
  { re: /록펠러|Rockefeller\s*Center|Top\s*of\s*the\s*Rock/i, en: "Rockefeller Center Top of the Rock" },
  { re: /9\.?11\s*메모리얼|Ground\s*Zero/i, en: "9/11 Memorial New York" },
  { re: /황소\s*동상|Charging\s*Bull/i, en: "Wall Street Charging Bull New York" },
  { re: /나이아가라\s*시티\s*크루즈|Niagara\s*City\s*Cruises/i, en: "Niagara Falls cruise boat mist" },
  { re: /테[를]?[르]?지\s*국립\s*공원|Terelj\s*National\s*Park/i, en: "Terelj National Park" },
  { re: /거북\s*바위|Turtle\s*Rock/i, en: "Turtle Rock" },
  { re: /아ri?ya발\s*사원|아리{1,2}ya?발\s*사원|Ariyabal/i, en: "Ariyabal Temple" },
  { re: /(?:자이승|Zaisan)/i, en: "Zaisan Memorial" },
  { re: /수흐?바타르|Sukhbaatar/i, en: "Sukhbaatar Square" },
  { re: /(?:칭기즈|징기스|Genghis)\s*칸/i, en: "Genghis Khan Statue" },
  { re: /로토루아\s*호수|Lake\s*Rotorua/i, en: "Lake Rotorua" },
  { re: /아그로돜|Agrodome/i, en: "Agrodome Rotorua sheep show" },
  { re: /스카이라인\s*곤돌라|Skyline\s*Rotorua/i, en: "Skyline Rotorua gondola luge" },
  { re: /와카레와레와|Whakarewarewa/i, en: "Whakarewarewa Maori Village geothermal" },
  { re: /미션\s*베이|Mission\s*Bay/i, en: "Mission Bay Auckland beach" },
  { re: /마이클\s*조셉\s*세비지|Michael\s*Joseph\s*Savage/i, en: "Michael Joseph Savage Memorial Auckland" },
  { re: /에덴\s*동산|Auckland\s*Domain/i, en: "Auckland Domain wintergardens" },
  { re: /밀포드\s*사운드|Milford\s*Sound/i, en: "Milford Sound New Zealand fiord" },
  { re: /카와라우\s*번지|Kawarau/i, en: "Kawarau Gorge Suspension Bridge" },
  { re: /애로우\s*타운|Arrowtown/i, en: "Arrowtown historic street" },
  { re: /카우리\s*번지|Nevis\s*Bungy/i, en: "Nevis Bungy Queenstown" },
  { re: /퀸즈?\s*타운\s*가든|Queenstown\s*Gardens/i, en: "Queenstown Gardens" },
  { re: /거울\s*호수|Mirror\s*Lakes/i, en: "Mirror Lakes Milford Sound" },
  { re: /호머\s*터널|Homer\s*Tunnel/i, en: "Homer Tunnel" },
  { re: /선한\s*양치기|Good\s*Shepherd/i, en: "Church of Good Shepherd Lake Tekapo" },
  { re: /푸카키\s*호수|Lake\s*Pukaki/i, en: "Lake Pukaki Mount Cook view" },
  { re: /해글리\s*공원|Hagley\s*Park/i, en: "Hagley Park Christchurch" },
  { re: /에이번\s*강|Avon\s*River/i, en: "Avon River Christchurch" },
  { re: /모나\s*베일|Mona\s*Vale/i, en: "Mona Vale Garden Christchurch" },
  { re: /바이아덕트|Christchurch\s*Tram/i, en: "Christchurch Tram city" },
  { re: /해밀턴\s*가든|Hamilton\s*Gardens/i, en: "Hamilton Gardens" },
  { re: /하무라나|Hamurana/i, en: "Hamurana Springs" },
  { re: /타우포\s*호수|Lake\s*Taupo/i, en: "Lake Taupo" },
  { re: /후카\s*폭포|Huka\s*Falls/i, en: "Huka Falls" },
  { re: /와이키테|와이오타푸|Wai-O-Tapu/i, en: "Wai-O-Tapu geothermal Rotorua" },
  { re: /레드우드|Redwoods\s*Whakarewarewa/i, en: "Redwoods Whakarewarewa Forest" },
  { re: /와이토모|Waitomo/i, en: "Waitomo Glowworm Caves" },
  { re: /울루루|Uluru|Ayers\s*Rock/i, en: "Uluru Ayers Rock sunset" },
  { re: /그레이트\s*배리어\s*리프|Great\s*Barrier\s*Reef/i, en: "Great Barrier Reef aerial" },
  { re: /폴리네시안\s*스파|Polynesian\s*Spa/i, en: "Polynesian Spa Rotorua" },
  { re: /쿠메우|Kumeu/i, en: "Kumeu wine region Auckland" },
  { re: /후지\s*산|후지산|Mount\s*Fuji|富士/i, en: "Mount Fuji Japan" },
  { re: /체르마트|Zermatt/i, en: "Zermatt Matterhorn village Switzerland" },
  { re: /마테호른|Matterhorn/i, en: "Matterhorn Zermatt Switzerland peak view" },
  { re: /로이커바트|Leukerbad/i, en: "Leukerbad alpine thermal spa Switzerland" },
  { re: /몽트뢰|Montreux/i, en: "Montreux Lake Geneva Switzerland waterfront" },
  { re: /시옹성|Chillon|쉴롱/i, en: "Chillon Castle Lake Geneva Switzerland" },
  { re: /하이델베르크|Heidelberg/i, en: "Heidelberg Castle old bridge Germany" },
  { re: /취리히|Zurich|취리흐/i, en: "Zurich Grossmunster lake waterfront Switzerland" },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: 리기≠승리기념탑 — Baltic Victory Monument bleed 금지 — manifest
  { re: /리기산|(?<![가-힣])리기(?![가-힣])|\bRigi\b/i, en: "Mount Rigi Switzerland cogwheel railway view" },
  { re: /인터라켄|Interlaken/i, en: "Interlaken Swiss Alps twin lakes view" },
  { re: /콜로세움|Colosseum/i, en: "Colosseum Rome exterior" },
  { re: /사그라다\s*파밀리아|Sagrada\s*Familia/i, en: "Sagrada Familia Barcelona exterior" },
  { re: /스위스\s*알프스|Swiss\s*Alps|Matterhorn/i, en: "Swiss Alps Matterhorn scenic" },
  { re: /페트라|Petra/i, en: "Petra Treasury Jordan" },
  { re: /마라케시|Marrakech|Marrakesh/i, en: "Marrakech Jemaa el-Fnaa square" },
  { re: /리우\s*데\s*자네이로|리오\s*데\s*자네이로|Rio\s*de\s*Janeiro/i, en: "Rio de Janeiro Christ the Redeemer" },
  { re: /세\s*자매\s*봉|Three\s*Sisters/i, en: "Three Sisters Blue Mountains" },
  { re: /에코\s*포인트|Echo\s*Point/i, en: "Echo Point Blue Mountains" },
  { re: /시드니\s*동물원|Taronga/i, en: "Taronga Zoo Sydney" },
  { re: /세인트\s*메?리(?:스)?\s*대성당|St\s*Mary/i, en: "St Marys Cathedral Sydney" },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: Palace/Bird Island는 SPOT — trip SSOT·gap-fill spot scan — manifest
  { re: /팔레스\s*오브\s*파인\s*아트|Palace\s*of\s*Fine\s*Arts/i, en: "Palace of Fine Arts San Francisco" },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: Saipan PIC·북섬 POI — bare Saipan 반복 금지 — manifest
  { re: /천혜의\s*자연\s*새섬|Bird\s*Island/i, en: "Saipan Bird Island" },
  { re: /PACIFIC\s*ISLANDS\s*CLUB|PIC\s*SAIPAN|사이판\s*PIC|Pacific\s*Islands\s*Club/i, en: "Pacific Islands Club Saipan" },
  { re: /마나가하|Managaha/i, en: "Managaha Island Saipan" },
  { re: /만세\s*절벽|Suicide\s*Cliff/i, en: "Suicide Cliff Saipan" },
  { re: /한국인\s*위령탑|Korean\s*(?:Peace\s*)?Memorial/i, en: "Korean Peace Memorial Saipan" },
  { re: /조텐(?:\s*쇼핑)?|Joeten/i, en: "Joeten Shopping Center Saipan" },
  { re: /라플린|Laughlin/i, en: "Laughlin Colorado River casino strip" },
  { re: /코닥\s*극장|Kodak\s*Theatre|TCL\s*Chinese/i, en: "TCL Chinese Theatre Hollywood" },
  { re: /니지노마츠바라|Nijinomatsubara|虹の松原/u, en: "Nijinomatsubara pine grove Saga Japan" },
  { re: /KK\s*스타\s*라운지|KK\s*Star\s*Lounge/i, en: "Kota Kinabalu waterfront sunset" },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: Alaska port days — 주노/케치칸 ≠ Glacier Bay catch-all — manifest
  { re: /껌벽/i, en: "Juneau Waterfront Alaska" },
  { re: /주노|Juneau/i, en: "Juneau Alaska waterfront" },
  { re: /케치칸|Ketchikan/i, en: "Ketchikan Alaska totem poles" },
  { re: /스카그웨이|스캐그웨이|Skagway|화이트\s*패스|White\s*Pass/i, en: "White Pass Yukon Railroad Skagway" },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: 단독 빙하 ≠ Glacier Bay Alaska (노르웨이 피요르드) — manifest
  { re: /글래시어\s*베이|Glacier\s*Bay/i, en: "Glacier Bay Alaska cruise" },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: Baltic·Warsaw POI — 빌라누프·체시스 — manifest
  { re: /빌라누프|Wilanow|Wilanów/i, en: "Wilanow Palace Warsaw" },
  { re: /체시스|Cesis|Cēsis/i, en: "Cesis Castle Latvia" },
  { re: /시굴다|Sigulda/i, en: "Sigulda Castle Latvia" },
  { re: /투라이다|Turaida/i, en: "Turaida Castle Latvia" },
  { re: /쿠트마니스|Gutmanis|Gūtmaņi/i, en: "Gutmanis Cave Sigulda Latvia" },
  { re: /카드리오르그|Kadriorg/i, en: "Kadriorg Palace Tallinn Estonia" },
] as const

export const SCHEDULE_CITY_KO_REGEX_RULES: ReadonlyArray<{ re: RegExp; en: string }> = [
  { re: /부르사|Bursa/i, en: "Bursa Grand Mosque Turkey" },
  { re: /이스탄불|Istanbul|İstanbul/i, en: "Blue Mosque Istanbul" },
  { re: /앙카라|Ankara/i, en: "Anitkabir Ankara" },
  { re: /안탈리아|Antalya/i, en: "Antalya Old Town" },
  { re: /아이발릭|Ayvalik|Ayvalık/i, en: "Ayvalik Aegean coast Turkey" },
  { re: /튀르키예|터키|Turkey/i, en: "Blue Mosque Istanbul" },
  { re: /상해|사해|上海/u, en: "Shanghai skyline night" },
  { re: /퍼블릭 마켓|Pike Place|Public Market/i, en: "Pike Place Market Seattle" },
  { re: /게스웍|Gas Works/i, en: "Gas Works Park Seattle" },
  { re: /스페이스 니들|Space Needle/i, en: "Space Needle Seattle" },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: 단독 빙하 ≠ Glacier Bay Alaska (노르웨이 피요르드) — manifest
  { re: /알래스카|Alaska/i, en: "Glacier Bay Alaska cruise" },
  { re: /인컨타라|Xiangshawan|响沙湾/i, en: "Xiangshawan Desert Ordos Inner Mongolia" },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: Ordos 기마상 — 오르도스 문맥만 (단독 칭기즈≠Ordos) — manifest
  { re: /오르도스|Ordos/i, en: "Genghis Khan Statue Ordos" },
  { re: /타슈켄트|Tashkent|타슈켄/i, en: 'Tashkent' },
  { re: /사마르칸트|Samarkand/i, en: 'Samarkand' },
  { re: /부하라|Bukhara/i, en: "Bukhara old city Uzbekistan" },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: 북경 도시허브=Beijing (자금성 POI는 SPOT) — manifest
  { re: /북경|베이징|北京/u, en: 'Beijing' },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: India 도시허브 — 자이푸르≠Hawa Mahal 과매핑 금지 — manifest
  { re: /자이푸르|Jaipur/i, en: 'Jaipur' },
  { re: /뉴\s*델리|뉴델리|델리|New\s*Delhi|\bDelhi\b/i, en: 'Delhi' },
  { re: /아그라|\bAgra\b/i, en: 'Agra' },
  { re: /바라나시|Varanasi|Banaras/i, en: 'Varanasi' },
  { re: /광저우|광주|广州/u, en: "Guangzhou skyline night" },
  { re: /심천|深圳/u, en: "Shenzhen skyline night" },
  { re: /도쿄|東京/u, en: "Tokyo street night" },
  { re: /오키나와|沖縄/u, en: "Okinawa beach coast" },
  { re: /미야코지마|宮古島/u, en: "Miyakojima beach" },
  { re: /마이파리(?:\s*열대\s*과수원)?/u, en: "Miyakojima Tropical Fruit Garden" },
  { re: /17\s*엔드|17엔드/u, en: "Yonaha Maehama Beach Miyakojima" },
  { re: /토오리이케|東平安名/u, en: "Toriike Pond Miyakojima" },
  { re: /이라부\s*대교|伊良部/u, en: "Irabu Bridge Miyakojima" },
  { re: /해중공원/u, en: "Miyakojima Haejung Park" },
  { re: /히가시헨나\s*곶|東平安名岬/u, en: "Higashi-Hennazaki Cape Miyakojima" },
  { re: /유키시오(?:\s*뮤지엄)?/u, en: "Yuki Snow Museum Miyakojima" },
  { re: /조개박물관/u, en: "Miyakojima Shell Museum" },
  { re: /시기라\s*오공\s*온센/u, en: "Shigira Ogon Onsen Miyakojima" },
  { re: /교토|京都/u, en: "Kyoto temple street" },
  { re: /후쿠오카|福岡/u, en: "Fukuoka city night" },
  { re: /삿포로|札幌/u, en: "Sapporo snow city street" },
  { re: /나고야|名古屋/u, en: "Nagoya castle view" },
  { re: /요코하마|横浜/u, en: "Yokohama bay night" },
  { re: /(?<![가-힣])파리(?![가-힣])/u, en: "Paris city skyline" },
  { re: /(?<!(?:고대\s{0,2}))(?<![가-힣])로마(?!시대)/u, en: "Rome Colosseum view" },
  { re: /바르셀로나/u, en: "Barcelona Sagrada Familia exterior" },
  { re: /런던/u, en: "London Thames skyline" },
  { re: /뉴욕/u, en: "New York Manhattan skyline" },
  { re: /연길/u, en: "Yanji Korean quarter winter street" },
  { re: /제주/u, en: "Jeju coast view" },
  { re: /부산/u, en: "Busan Gamcheon village" },
  { re: /방콕/u, en: "Bangkok Wat Arun temple" },
  { re: /치앙마이/u, en: "Chiang Mai old city temple" },
  { re: /파타야/u, en: "Pattaya beach sunset" },
  { re: /호이안|會安|Hoi\s*An/u, en: "Hoi An Ancient Town / lantern-lit street / eye-level" },
  { re: /다낭/u, en: "Da Nang Han River / Dragon Bridge waterfront skyline / wide angle" },
  { re: /하노이/u, en: "Hanoi Old Quarter" },
  { re: /호치민(?:시)?(?!\s*생가)|호찌민(?!\s*생가)|Ho\s*Chi\s*Minh\s*City/iu, en: "Ben Thanh Market Ho Chi Minh" },
  { re: /세부/u, en: "Cebu tropical beach" },
  { re: /보라카이/u, en: "Boracay white beach" },
  { re: /발리/u, en: "Bali rice terrace view" },
  { re: /시드니|悉尼/u, en: "Sydney Opera House harbour" },
  { re: /멜버른|멜번/u, en: "Melbourne laneway street" },
  { re: /홍콩|香港/u, en: "Hong Kong Victoria Harbour night" },
  { re: /마카오|澳門/u, en: "Macau Senado square" },
  { re: /타이페이|台北/u, en: "Taipei night market street" },
  { re: /하와이|호놀룰루|Honolulu/i, en: "Honolulu Waikiki beach" },
  { re: /두바이|Dubai/i, en: "Burj Khalifa Dubai skyline" },
  { re: /아부다비|Abu\s*Dhabi/i, en: "Sheikh Zayed Grand Mosque Abu Dhabi" },
  { re: /괌|Guam/i, en: "Guam Tumon beach" },
  { re: /투몬|Tumon/i, en: "Tumon Bay Guam beach" },
  { re: /아시아\s*타이|Asia\s*Typhoon/i, en: "Asia Typhoon Waterpark Guam" },
  { re: /플라자\s*데\s*스페|Plaza\s*de\s*Espana/i, en: "Plaza de Espana Guam Spanish steps" },
  { re: /아푸간|Apugan|Apaca/i, en: "Fort Apugan Guam hilltop view" },
  { re: /돈키\s*빌리지|Donkey\s*Village/i, en: "Donkey Village Guam" },
  // REGRESSION-FREEZE[schedule-poi-regex-ssot]: Ipan must not substring-match Saipan — manifest
  { re: /이파오|\bIpan\b|Tumon\s*Bay/i, en: "Tumon Bay Guam beach" },
  { re: /알마티|Almaty/i, en: 'Almaty' },
  { re: /콜사이|콜사이호수|Kolsai|Kolsay/i, en: 'Kolsai Lakes' },
  { re: /카인디|Kaindy/i, en: "Kaindy Lake Kazakhstan sunken forest" },
  { re: /시애틀|Seattle/i, en: "Seattle Space Needle waterfront" },
  { re: /리츠린|Ritsurin/i, en: "Ritsurin Garden Takamatsu Japan" },
  { re: /고토히라|Kotohira|金刀比羅/i, en: "Kotohira Shrine Japan stone steps" },
  { re: /나오시마|Naoshima/i, en: "Naoshima art island Japan yellow pumpkin" },
  { re: /지중\s*미술관|Chichu\s*Art/i, en: "Chichu Art Museum Naoshima Tadao Ando" },
  { re: /베넷세|Benesse/i, en: "Benesse House Museum Naoshima" },
  { re: /이우환|Lee\s*Ufan/i, en: "Lee Ufan Museum Naoshima" },
  { re: /다카마츠|Takamatsu/i, en: "Ritsurin Garden Takamatsu Japan" },
  { re: /사이판|Saipan/i, en: "Saipan" },
  { re: /캘거리|Calgary/i, en: "Calgary Tower downtown skyline" },
  { re: /밴프|Banff/i, en: "Banff townsite Rocky Mountains" },
  { re: /피렌체|Florence|Firenze/i, en: "Florence Duomo historic center" },
  { re: /베니스|Venice|Venezia/i, en: "Venice Grand Canal gondolas" },
  { re: /밀라노|Milan|Milano/i, en: "Milan Cathedral Duomo square" },
  { re: /빌니우스|Vilnius/i, en: "Vilnius Old Town Lithuania" },
  { re: /리가|Riga/i, en: "Riga Latvia Art Nouveau street" },
  { re: /탈린|Tallinn/i, en: "Tallinn Old Town Estonia" },
  { re: /헬싱키|Helsinki/i, en: "Helsinki Senate Square Finland" },
  { re: /스톡홀름|Stockholm/i, en: "Stockholm Gamla Stan waterfront" },
  { re: /오슬로|Oslo/i, en: "Oslo Norway harbor fjord view" },
  { re: /코펜하겐|Copenhagen|København/i, en: "Copenhagen Nyhavn waterfront" },
  { re: /베르겐|Bergen/i, en: "Bergen Norway Bryggen harbor" },
  { re: /바르샤바|Warsaw/i, en: "Warsaw Old Town square Poland" },
  { re: /칭다오|청도|Qingdao/i, en: "Qingdao Zhanqiao Pier" },
  { re: /대련|다롄|大连/u, en: "Dalian" },
  { re: /여순|旅顺|Lushun/i, en: "Lushun Dalian" },
  { re: /나이로비|Nairobi/i, en: "Nairobi Kenya city skyline" },
  { re: /케이프타운|Cape\s*Town/i, en: "Cape Town Table Mountain" },
  { re: /모나코|Monaco/i, en: "Monaco Monte Carlo harbor" },
  { re: /베른|Bern/i, en: "Bern Switzerland old town" },
  { re: /하문|샤먼|Xiamen|厦门/u, en: "Xiamen harbor skyline" },
  { re: /복주|푸저우|福州|Fuzhou/u, en: "Fuzhou skyline" },
  { re: /(?<!(?:고대\s{0,2}))로마(?!시대)/u, en: "Rome Colosseum view" },
  { re: /리마|Lima/i, en: "Lima Peru Miraflores coastal cliff park" },
  { re: /쿠스코|Cusco|Cuzco/i, en: "Cusco Peru Plaza de Armas" },
  { re: /라파즈|La\s*Paz/i, en: "La Paz Bolivia cable car city view" },
  { re: /우유니|Uyuni/i, en: "Salar de Uyuni salt flats Bolivia" },
  { re: /이과수|Iguazu/i, en: "Iguazu Falls waterfall panorama" },
  { re: /리오데자네이로|Rio\s*de\s*Janeiro/i, en: "Rio de Janeiro Christ the Redeemer view" },
  { re: /로스엔젤레스|Los\s*Angeles|LA\b/i, en: "Los Angeles Griffith Observatory city view" },
  { re: /워싱턴\s*DC|Washington\s*DC/i, en: "Washington DC National Mall monuments" },
  { re: /토론토|Toronto/i, en: "Toronto CN Tower skyline" },
  { re: /몬트리올|Montreal/i, en: "Montreal Old Port waterfront" },
  { re: /퀘벡|Quebec/i, en: "Quebec City Old Town Chateau Frontenac" },
  { re: /나이아가라|Niagara/i, en: "Niagara Falls waterfall wide angle" },
  { re: /몰디브|Maldives/i, en: "Maldives overwater villa lagoon sunset" },
  { re: /나트랑|Nha Trang/i, en: "Nha Trang beach Vietnam" },
  { re: /달랏|Da Lat|Dalat/i, en: "Da Lat Vietnam highland city" },
  { re: /쿠알라룸푸르|Kuala\s*Lumpur/i, en: "Kuala Lumpur Petronas Twin Towers" },
  { re: /말라카|Malacca|Melaka/i, en: "Malacca historic city Malaysia" },
  { re: /페낭|Penang|George\s*Town/i, en: "George Town Penang Malaysia" },
  { re: /랑카위|Langkawi/i, en: "Langkawi island Malaysia" },
  { re: /오클랜드|Auckland/i, en: "Auckland Sky Tower harbour" },
  { re: /로토루아|Rotorua/i, en: "Rotorua geothermal valley" },
  { re: /퀸즈?\s*타운|퀸스\s*타운|Queenstown/i, en: "Queenstown Lake Wakatipu" },
  { re: /크라이스트\s*처치|Christchurch/i, en: "Christchurch Cathedral square" },
  { re: /골드\s*코스트|Gold\s*Coast/i, en: "Surfers Paradise Gold Coast beach" },
  { re: /케언즈|Cairns/i, en: "Cairns Great Barrier Reef gateway" },
  { re: /퍼스|Perth/i, en: "Perth Kings Park skyline" },
  { re: /브리즈번|Brisbane/i, en: "Brisbane Story Bridge" },
  { re: /뉴질랜드|New\s*Zealand/i, en: "New Zealand Milford Sound landscape" },
  { re: /호주|Australia/i, en: "Australia Sydney Opera House harbour" },
  { re: /리우\s*데\s*자네이로|Rio\s*de\s*Janeiro/i, en: "Rio de Janeiro Christ the Redeemer view" },
  { re: /마라케시|Marrakech/i, en: "Marrakech medina Morocco" },
  { re: /하코네|Hakone/i, en: "Hakone hot spring Mount Fuji view" },
  { re: /닛코|Nikko/i, en: "Nikko Toshogu Shrine" },
] as const
function firstMatchingEn(rules: ReadonlyArray<SchedulePoiRegexRule>, h: string): string | null {
  for (const { re, en } of rules) {
    if (re.test(h)) return en
  }
  return null
}

/** routeText·본문 세그먼트 — 랜드마크/명소 우선 */
export function routeContextualNationalAssemblyEnglish(
  seg: string,
  routeText: string | null | undefined,
): string {
  if (!/국회의사당/u.test(seg)) return ''
  const ctx = `${String(routeText ?? '')} ${seg}`
  if (/(?:워싱턴|Washington\s*D\.?\s*C\.?|미국\s*동부|미\s*동부)/i.test(ctx)) {
    return 'United States Capitol dome Washington DC'
  }
  if (/부다페스트|헝가리/i.test(ctx)) return 'Hungarian Parliament Budapest'
  if (/비엔나|오스트리아|Wien|Vienna/i.test(ctx)) return 'Austrian Parliament Vienna'
  if (/프라하|체코/i.test(ctx)) return 'Prague Castle'
  return ''
}

export function firstMatchingScheduleSpotEn(haystack: string): string | null {
  const h = String(haystack ?? '').trim()
  if (!h) return null
  return firstMatchingEn(SCHEDULE_SPOT_KO_REGEX_RULES, h)
}

/** routeText·본문 세그먼트 — 도시 폴백 */
export function firstMatchingScheduleCityEn(haystack: string): string | null {
  const h = String(haystack ?? '').trim()
  if (!h) return null
  return firstMatchingEn(SCHEDULE_CITY_KO_REGEX_RULES, h)
}

/** 명소 → 도시 순으로 첫 매칭 */
export function firstMatchingSchedulePoiEn(haystack: string): string | null {
  return firstMatchingScheduleSpotEn(haystack) ?? firstMatchingScheduleCityEn(haystack)
}

/** routeText·본문 — 등장 순 전체 명소 매칭 */
export function findAllScheduleSpotMatchesInText(text: string): Array<{ index: number; en: string }> {
  const haystack = String(text ?? '')
  const hits: Array<{ index: number; en: string }> = []
  for (const { re, en } of SCHEDULE_SPOT_KO_REGEX_RULES) {
    const m = haystack.match(re)
    if (m && m.index != null) hits.push({ index: m.index, en })
  }
  hits.sort((a, b) => a.index - b.index)
  return hits
}

/** regex SSOT 영문 키 — weak-opaque·SSOT 판별용 */
export function getSchedulePoiRegexEnglishKeys(): ReadonlySet<string> {
  return SCHEDULE_POI_REGEX_EN_KEYS
}

/** 한글 세그먼트 — regex 우선(오매핑 방지), finalize 시도 */
export function englishFromScheduleKoreanSegmentWithRegex(seg: string): string {
  const t = String(seg ?? '').trim()
  if (!t) return ''
  const spot = firstMatchingScheduleSpotEn(t)
  if (spot) {
    try {
      return finalizeScheduleImageKeyword(spot)
    } catch {
      return spot
    }
  }
  const fromPoi = mapKoreanPoiSegment(t)
  if (fromPoi) {
    try {
      return finalizeScheduleImageKeyword(fromPoi)
    } catch {
      /* continue */
    }
  }
  const fromDest = mapDestination(t)
  if (fromDest && fromDest !== t && !/[\uAC00-\uD7AF]/u.test(fromDest)) {
    try {
      return finalizeScheduleImageKeyword(fromDest)
    } catch {
      /* continue */
    }
  }
  const city = firstMatchingScheduleCityEn(t)
  if (city) {
    try {
      return finalizeScheduleImageKeyword(city)
    } catch {
      return city
    }
  }
  return ''
}

const SCHEDULE_POI_REGEX_EN_KEYS: ReadonlySet<string> = new Set(
  [...SCHEDULE_SPOT_KO_REGEX_RULES, ...SCHEDULE_CITY_KO_REGEX_RULES].map(({ en }) =>
    normalizeSemanticPoiKey(en),
  ),
)
