ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "termsConsentAt" TIMESTAMPTZ;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "termsConsentVersion" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "ageConfirmedAt" TIMESTAMPTZ;
